// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UARSaveWorldPin__PythonCallable")
extern class ARSaveWorldPin__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstARSaveWorldPin__PythonCallable(ARSaveWorldPin__PythonCallable) from ARSaveWorldPin__PythonCallable {
}