// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UARTypesDummyClass")
@:include("ARTypes.h")
extern class ARTypesDummyClass extends Object {
}

@:forward()
@:nativeGen
abstract ConstARTypesDummyClass(ARTypesDummyClass) from ARTypesDummyClass {
}