// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAutoClusterFractureCommand")
@:include("AutoClusterFracture.h")
extern class AutoClusterFractureCommand extends Object {
}

@:forward()
@:nativeGen
abstract ConstAutoClusterFractureCommand(AutoClusterFractureCommand) from AutoClusterFractureCommand {
}