// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FBakedFloatCustomAttribute")
@:include("Animation/CustomAttributes.h")
extern class BakedFloatCustomAttribute {
	public var AttributeName: FName;
	public var FloatCurve: SimpleCurve;
}