// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlueprintEditorTutorial_C")
extern class BlueprintEditorTutorial_C extends EditorTutorial {
}

@:forward()
@:nativeGen
abstract ConstBlueprintEditorTutorial_C(BlueprintEditorTutorial_C) from BlueprintEditorTutorial_C {
}