// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UComponentTrackingDeactivatedSignature__PythonCallable")
extern class ComponentTrackingDeactivatedSignature__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstComponentTrackingDeactivatedSignature__PythonCallable(ComponentTrackingDeactivatedSignature__PythonCallable) from ComponentTrackingDeactivatedSignature__PythonCallable {
}