// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FCullDistanceSizePair")
@:include("Engine/CullDistanceVolume.h")
extern class CullDistanceSizePair {
	public var Size: cpp.Float32;
	public var CullDistance: cpp.Float32;
}