// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDeviceProfileFragment")
@:include("DeviceProfiles/DeviceProfileFragment.h")
extern class DeviceProfileFragment extends Object {
}

@:forward()
@:nativeGen
abstract ConstDeviceProfileFragment(DeviceProfileFragment) from DeviceProfileFragment {
}