// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EAudioBusChannels")
@:include("Sound/AudioBus.h")
extern enum EAudioBusChannels {
	Mono;
	Stereo;
	EAudioBusChannels_MAX;
}