// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EFBXNormalImportMethod")
@:include("Factories/FbxMeshImportData.h")
extern enum EFBXNormalImportMethod {
	FBXNIM_ComputeNormals;
	FBXNIM_ImportNormals;
	FBXNIM_ImportNormalsAndTangents;
	FBXNIM_MAX;
}