// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EFixedFoveatedRenderingLevel")
@:include("OculusFunctionLibrary.h")
extern enum EFixedFoveatedRenderingLevel {
	FFR_Off;
	FFR_Low;
	FFR_Medium;
	FFR_High;
	FFR_HighTop;
	FFR_MAX;
}