// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EFrictionCombineMode.Type")
@:include("PhysicsSettingsEnums.h")
extern enum EFrictionCombineMode {
	Average;
	Min;
	Multiply;
	Max;
	EFrictionCombineMode_MAX;
}