// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EKinematicBonesUpdateToPhysics.Type")
@:include("Components/SkeletalMeshComponent.h")
extern enum EKinematicBonesUpdateToPhysics {
	SkipSimulatingBones;
	SkipAllBones;
	EKinematicBonesUpdateToPhysics_MAX;
}