// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ETextureDownscaleOptions")
@:include("Engine/TextureDefines.h")
extern enum ETextureDownscaleOptions {
	Default;
	Unfiltered;
	SimpleAverage;
	Sharpen0;
	Sharpen1;
	Sharpen2;
	Sharpen3;
	Sharpen4;
	Sharpen5;
	Sharpen6;
	Sharpen7;
	Sharpen8;
	Sharpen9;
	Sharpen10;
	ETextureDownscaleOptions_MAX;
}