// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ETunnelBoundaryType")
@:include("K2Node_TunnelBoundary.h")
extern enum ETunnelBoundaryType {
	Unknown;
	EntrySite;
	InputSite;
	OutputSite;
	ETunnelBoundaryType_MAX;
}