// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EVirtualizationMode")
@:include("Sound/SoundBase.h")
extern enum EVirtualizationMode {
	Disabled;
	PlayWhenSilent;
	Restart;
	EVirtualizationMode_MAX;
}