// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UFractureUniformSettings")
@:include("FractureToolUniform.h")
extern class FractureUniformSettings extends FractureToolSettings {
	public var NumberVoronoiSitesMin: cpp.Int32;
	public var NumberVoronoiSitesMax: cpp.Int32;
}

@:forward()
@:nativeGen
abstract ConstFractureUniformSettings(FractureUniformSettings) from FractureUniformSettings {
	public extern var NumberVoronoiSitesMin(get, never): cpp.Int32;
	public inline extern function get_NumberVoronoiSitesMin(): cpp.Int32 return this.NumberVoronoiSitesMin;
	public extern var NumberVoronoiSitesMax(get, never): cpp.Int32;
	public inline extern function get_NumberVoronoiSitesMax(): cpp.Int32 return this.NumberVoronoiSitesMax;
}