// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGenericGameplayTaskDelegate__PythonCallable")
extern class GenericGameplayTaskDelegate__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstGenericGameplayTaskDelegate__PythonCallable(GenericGameplayTaskDelegate__PythonCallable) from GenericGameplayTaskDelegate__PythonCallable {
}