// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FInAppPurchaseProductInfo")
@:include("Interfaces/OnlineStoreInterface.h")
extern class InAppPurchaseProductInfo {
	public var Identifier: FString;
	public var TransactionIdentifier: FString;
	public var DisplayName: FString;
	public var DisplayDescription: FString;
	public var DisplayPrice: FString;
	public var RawPrice: cpp.Float32;
	public var CurrencyCode: FString;
	public var CurrencySymbol: FString;
	public var DecimalSeparator: FString;
	public var GroupingSeparator: FString;
	public var ReceiptData: FString;
}