// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ULightMapVirtualTexture2D")
@:include("VT/LightmapVirtualTexture.h")
extern class LightMapVirtualTexture2D extends Texture2D {
	public var TypeToLayer: TArray<cpp.Int8>;
}

@:forward()
@:nativeGen
abstract ConstLightMapVirtualTexture2D(LightMapVirtualTexture2D) from LightMapVirtualTexture2D {
	public extern var TypeToLayer(get, never): TArray<cpp.Int8>;
	public inline extern function get_TypeToLayer(): TArray<cpp.Int8> return this.TypeToLayer;
}