// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FLocalizedAppName")
@:include("LuminRuntimeSettings.h")
extern class LocalizedAppName {
	public var LanguageCode: FString;
	public var AppName: FString;
}