// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ULuminARLightEstimate")
@:include("LuminARTypes.h")
extern class LuminARLightEstimate extends ARBasicLightEstimate {
	public var AmbientIntensityNits: TArray<cpp.Float32>;

	public function GetAmbientIntensityNits(): cpp.Reference<TArray<cpp.Float32>>;
}

@:forward(GetAmbientIntensityNits)
@:nativeGen
abstract ConstLuminARLightEstimate(LuminARLightEstimate) from LuminARLightEstimate {
	public extern var AmbientIntensityNits(get, never): TArray<cpp.Float32>;
	public inline extern function get_AmbientIntensityNits(): TArray<cpp.Float32> return this.AmbientIntensityNits;
}