// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMetaDataKeyGatherSpecification")
@:include("LocalizationTargetTypes.h")
extern class MetaDataKeyGatherSpecification {
	public var MetaDataKey: MetaDataKeyName;
	public var TextNamespace: FString;
	public var TextKeyPattern: MetaDataTextKeyPattern;
}