// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMovieSceneEvaluationHookEventContainer")
@:include("EntitySystem/MovieSceneEvaluationHookSystem.h")
extern class MovieSceneEvaluationHookEventContainer {
	public var Events: TArray<MovieSceneEvaluationHookEvent>;
}