// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMovieSceneEvaluationGroupLUTIndex")
@:include("Evaluation/MovieSceneEvaluationField.h")
extern class MovieSceneEvaluationGroupLUTIndex {
	public var NumInitPtrs: cpp.Int32;
	public var NumEvalPtrs: cpp.Int32;
}