// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneCameraShakeEvaluator")
@:include("Evaluation/MovieSceneCameraShakeTemplate.h")
extern class MovieSceneCameraShakeEvaluator extends Object {
}

@:forward()
@:nativeGen
abstract ConstMovieSceneCameraShakeEvaluator(MovieSceneCameraShakeEvaluator) from MovieSceneCameraShakeEvaluator {
}