// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnEditableTextChangedEvent__PythonCallable")
extern class OnEditableTextChangedEvent__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstOnEditableTextChangedEvent__PythonCallable(OnEditableTextChangedEvent__PythonCallable) from OnEditableTextChangedEvent__PythonCallable {
}