// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPaintModeSettings")
@:include("PaintModeSettings.h")
extern class PaintModeSettings extends MeshPaintSettings {
	public var PaintMode: EPaintMode;
	public var VertexPaintSettings: VertexPaintSettings;
	public var TexturePaintSettings: TexturePaintSettings;
}

@:forward()
@:nativeGen
abstract ConstPaintModeSettings(PaintModeSettings) from PaintModeSettings {
	public extern var PaintMode(get, never): EPaintMode;
	public inline extern function get_PaintMode(): EPaintMode return this.PaintMode;
	public extern var VertexPaintSettings(get, never): VertexPaintSettings;
	public inline extern function get_VertexPaintSettings(): VertexPaintSettings return this.VertexPaintSettings;
	public extern var TexturePaintSettings(get, never): TexturePaintSettings;
	public inline extern function get_TexturePaintSettings(): TexturePaintSettings return this.TexturePaintSettings;
}