// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FVehicleEngineData")
@:include("WheeledVehicleMovementComponent4W.h")
extern class VehicleEngineData {
	public var TorqueCurve: RuntimeFloatCurve;
	public var MaxRPM: cpp.Float32;
	public var MOI: cpp.Float32;
	public var DampingRateFullThrottle: cpp.Float32;
	public var DampingRateZeroThrottleClutchEngaged: cpp.Float32;
	public var DampingRateZeroThrottleClutchDisengaged: cpp.Float32;
}