// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UActorFactoryBasicShape")
@:include("ActorFactories/ActorFactoryBasicShape.h")
@:structAccess
extern class ActorFactoryBasicShape extends ActorFactoryStaticMesh {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstActorFactoryBasicShape(ActorFactoryBasicShape) from ActorFactoryBasicShape {
}