// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AIntervalGizmoActor")
@:include("BaseGizmos/IntervalGizmo.h")
extern class AIntervalGizmoActor extends AGizmoActor {
	public var UpIntervalComponent: TObjectPtr<UGizmoLineHandleComponent>;
	public var DownIntervalComponent: TObjectPtr<UGizmoLineHandleComponent>;
	public var ForwardIntervalComponent: TObjectPtr<UGizmoLineHandleComponent>;
}
