// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ANavigationData")
@:include("NavigationData.h")
extern class ANavigationData extends AActor {
	public var RenderingComp: TObjectPtr<UPrimitiveComponent>;
	public var NavDataConfig: FNavDataConfig;
	public var bEnableDrawing: Bool;
	public var bForceRebuildOnLoad: Bool;
	public var bAutoDestroyWhenNoNavigation: Bool;
	public var bCanBeMainNavData: Bool;
	public var bCanSpawnOnRebuild: Bool;
	public var bRebuildAtRuntime_DEPRECATED: Bool;
	public var RuntimeGeneration: ERuntimeGenerationType;
	public var ObservedPathsTickInterval: cpp.Float32;
	public var DataVersion: cpp.UInt32;
	public var SupportedAreas: TArray<FSupportedAreaData>;
}
