// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimBlueprintClassSubsystem_PropertyAccess")
@:include("Animation/AnimBlueprintClassSubsystem_PropertyAccess.h")
@:structAccess
extern class AnimBlueprintClassSubsystem_PropertyAccess extends Object {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstAnimBlueprintClassSubsystem_PropertyAccess(AnimBlueprintClassSubsystem_PropertyAccess) from AnimBlueprintClassSubsystem_PropertyAccess {
}