// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimCurveCompressionSettings")
@:include("Animation/AnimCurveCompressionSettings.h")
extern class AnimCurveCompressionSettings extends Object {
	public var Codec: cpp.Star<AnimCurveCompressionCodec>;
}

@:forward()
@:nativeGen
abstract ConstAnimCurveCompressionSettings(AnimCurveCompressionSettings) from AnimCurveCompressionSettings {
	public extern var Codec(get, never): cpp.Star<AnimCurveCompressionCodec.ConstAnimCurveCompressionCodec>;
	public inline extern function get_Codec(): cpp.Star<AnimCurveCompressionCodec.ConstAnimCurveCompressionCodec> return this.Codec;
}