// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAnimNode_BlendListByEnum")
@:include("AnimNodes/AnimNode_BlendListByEnum.h")
@:valueType
extern class AnimNode_BlendListByEnum extends AnimNode_BlendListBase {

	@:native("FAnimNode_BlendListByEnum") public function new();
	@:native("FAnimNode_BlendListByEnum") public static function make(EnumToPoseIndex: TArray<ucpp.num.Int32>, ActiveEnumValue: ucpp.num.UInt8): AnimNode_BlendListByEnum ;
}