// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UARLightEstimate")
@:include("ARLightEstimate.h")
@:structAccess
extern class ARLightEstimate extends Object {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstARLightEstimate(ARLightEstimate) from ARLightEstimate {
}

@:forward
@:nativeGen
@:native("ARLightEstimate*")
abstract ARLightEstimatePtr(cpp.Star<ARLightEstimate>) from cpp.Star<ARLightEstimate> to cpp.Star<ARLightEstimate>{
	@:from
	public static extern inline function fromValue(v: ARLightEstimate): ARLightEstimatePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ARLightEstimate {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}