// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAudioBusFactory")
@:include("Factories/AudioBusFactory.h")
extern class AudioBusFactory extends Factory {
}

@:forward()
@:nativeGen
abstract ConstAudioBusFactory(AudioBusFactory) from AudioBusFactory {
}