// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAutoCompleteCommand")
@:include("ConsoleSettings.h")
@:valueType
extern class AutoCompleteCommand {
	public var Command: FString;
	public var Desc: FString;

	@:native("FAutoCompleteCommand") public function new();
	@:native("FAutoCompleteCommand") public static function make(Command: FString, Desc: FString): AutoCompleteCommand ;
}