// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AVisualLoggerRenderingActor")
@:include("VisualLoggerRenderingActor.h")
extern class AVisualLoggerRenderingActor extends AVisualLoggerRenderingActorBase {
}
