// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBehaviorTreeGraphNode_Service")
@:include("BehaviorTreeGraphNode_Service.h")
@:structAccess
extern class BehaviorTreeGraphNode_Service extends BehaviorTreeGraphNode {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstBehaviorTreeGraphNode_Service(BehaviorTreeGraphNode_Service) from BehaviorTreeGraphNode_Service {
}