// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlendSpaceGraph")
@:include("BlendSpaceGraph.h")
@:structAccess
extern class BlendSpaceGraph extends EdGraph {
	public var BlendSpace: cpp.Star<BlendSpace>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstBlendSpaceGraph(BlendSpaceGraph) from BlendSpaceGraph {
	public extern var BlendSpace(get, never): cpp.Star<BlendSpace.ConstBlendSpace>;
	public inline extern function get_BlendSpace(): cpp.Star<BlendSpace.ConstBlendSpace> return this.BlendSpace;
}