// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlueprintFindSessionsResultDelegate__PythonCallable")
extern class BlueprintFindSessionsResultDelegate__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstBlueprintFindSessionsResultDelegate__PythonCallable(BlueprintFindSessionsResultDelegate__PythonCallable) from BlueprintFindSessionsResultDelegate__PythonCallable {
}