// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlueprintEventNodeSpawner")
@:include("BlueprintEventNodeSpawner.h")
@:structAccess
extern class BlueprintEventNodeSpawner extends BlueprintNodeSpawner {
	public var EventFunc: cpp.Star<Function>;
	public var CustomEventName: FName;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstBlueprintEventNodeSpawner(BlueprintEventNodeSpawner) from BlueprintEventNodeSpawner {
	public extern var EventFunc(get, never): cpp.Star<Function.ConstFunction>;
	public inline extern function get_EventFunc(): cpp.Star<Function.ConstFunction> return this.EventFunc;
	public extern var CustomEventName(get, never): FName;
	public inline extern function get_CustomEventName(): FName return this.CustomEventName;
}

@:forward
@:nativeGen
@:native("BlueprintEventNodeSpawner*")
abstract BlueprintEventNodeSpawnerPtr(cpp.Star<BlueprintEventNodeSpawner>) from cpp.Star<BlueprintEventNodeSpawner> to cpp.Star<BlueprintEventNodeSpawner>{
	@:from
	public static extern inline function fromValue(v: BlueprintEventNodeSpawner): BlueprintEventNodeSpawnerPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): BlueprintEventNodeSpawner {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}