// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UCanvasPanel")
@:include("Components/CanvasPanel.h")
@:structAccess
extern class CanvasPanel extends PanelWidget {
	public function AddChildToCanvas(Content: cpp.Star<Widget>): cpp.Reference<cpp.Star<CanvasPanelSlot>>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstCanvasPanel(CanvasPanel) from CanvasPanel {
}