// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UCombineMeshesToolProperties")
@:include("CombineMeshesTool.h")
extern class CombineMeshesToolProperties extends InteractiveToolPropertySet {
	public var bIsDuplicateMode: Bool;
	public var OutputWriteTo: EBaseCreateFromSelectedTargetType;
	public var OutputNewName: FString;
	public var OutputExistingName: FString;
}

@:forward()
@:nativeGen
abstract ConstCombineMeshesToolProperties(CombineMeshesToolProperties) from CombineMeshesToolProperties {
	public extern var bIsDuplicateMode(get, never): Bool;
	public inline extern function get_bIsDuplicateMode(): Bool return this.bIsDuplicateMode;
	public extern var OutputWriteTo(get, never): EBaseCreateFromSelectedTargetType;
	public inline extern function get_OutputWriteTo(): EBaseCreateFromSelectedTargetType return this.OutputWriteTo;
	public extern var OutputNewName(get, never): FString;
	public inline extern function get_OutputNewName(): FString return this.OutputNewName;
	public extern var OutputExistingName(get, never): FString;
	public inline extern function get_OutputExistingName(): FString return this.OutputExistingName;
}