// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UComponentOnClickedSignature__PythonCallable")
extern class ComponentOnClickedSignature__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstComponentOnClickedSignature__PythonCallable(ComponentOnClickedSignature__PythonCallable) from ComponentOnClickedSignature__PythonCallable {
}