// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UControlRigBlueprint")
@:include("ControlRigBlueprint.h")
@:valueType
extern class ControlRigBlueprint extends Blueprint {
	public var RigGraphDisplaySettings: RigGraphDisplaySettings;
	public var HierarchySettings: RigHierarchySettings;
	public var VMRuntimeSettings: RigVMRuntimeSettings;
	public var VMCompileSettings: RigVMCompileSettings;
	public var PythonLogSettings: ControlRigPythonSettings;
	@:protected public var RigVMClient: RigVMClient;
	@:protected public var PublicGraphFunctions: TArray<RigVMGraphFunctionHeader>;
	@:protected public var FunctionReferenceNodeData: TArray<RigVMReferenceNodeData>;
	public var PinToOperandMap: TMap<FString, RigVMOperand>;
	public var DrawContainer: RigVMDrawContainer;
	public var Influences: RigInfluenceMapPerEvent;
	public var Hierarchy: ucpp.Ptr<RigHierarchy>;
	private var bSupportsInversion: Bool;
	private var bSupportsControls: Bool;
	private var SourceHierarchyImport: TSoftObjectPtr<Object>;
	private var SourceCurveImport: TSoftObjectPtr<Object>;
	private var SupportedEventNames: TArray<FName>;
	private var bExposesAnimatableControls: Bool;
	private var bAutoRecompileVM: Bool;
	private var bVMRecompilationRequired: Bool;
	private var bIsCompiling: Bool;
	private var VMRecompilationBracket: ucpp.num.Int32;
	private var Validator: ucpp.Ptr<ControlRigValidator>;
	private var DebugBoneRadius: ucpp.num.Float32;

	private function SuspendNotifications(bSuspendNotifs: Bool): Void;
	public function SetPreviewMesh(PreviewMesh: ucpp.Ptr<SkeletalMesh>, bMarkAsDirty: Bool): Void;
	public function SetAutoVMRecompile(bAutoRecompile: Bool): Void;
	public function RequestControlRigInit(): Void;
	public function RequestAutoVMRecompilation(): Void;
	public function RenameMemberVariable(InOldName: ucpp.Ref<FName>, InNewName: ucpp.Ref<FName>): Bool;
	public function RemoveModel(InName: FString, bSetupUndoRedo: Bool, bPrintPythonCommand: Bool): Bool;
	public function RemoveMemberVariable(InName: ucpp.Ref<FName>): Bool;
	public function RecompileVMIfRequired(): Void;
	public function RecompileVM(): Void;
	public function GetPreviewMesh(): ucpp.Ptr<SkeletalMesh>;
	public function GetOrCreateController(InGraph: ucpp.Ptr<RigVMGraph>): ucpp.Ptr<RigVMController>;
	public function GetModel(InEdGraph: ucpp.Ptr<EdGraph.ConstEdGraph>): ucpp.Ptr<RigVMGraph>;
	public function GetMemberVariables(): TArray<RigVMGraphVariableDescription>;
	public function GetLocalFunctionLibrary(): ucpp.Ptr<RigVMFunctionLibrary>;
	public function GetHierarchyController(): ucpp.Ptr<RigHierarchyController>;
	public function GetDefaultModel(): ucpp.Ptr<RigVMGraph>;
	public function GetCurrentlyOpenRigBlueprints(): TArray<ucpp.Ptr<ControlRigBlueprint>>;
	public function GetControlRigClass(): ucpp.Ptr<Class>;
	public function GetControllerByName(InGraphName: FString): ucpp.Ptr<RigVMController>;
	public function GetController(InGraph: ucpp.Ptr<RigVMGraph.ConstRigVMGraph>): ucpp.Ptr<RigVMController>;
	public function GetAvailableRigUnits(): TArray<ucpp.Ptr<Struct>>;
	public function GetAllModels(): TArray<ucpp.Ptr<RigVMGraph>>;
	public function GeneratePythonCommands(InNewBlueprintName: FString): TArray<FString>;
	public function CreateControlRig(): ucpp.Ptr<ControlRig>;
	public function ChangeMemberVariableType(InName: ucpp.Ref<FName>, InCPPType: FString, bIsPublic: Bool, bIsReadOnly: Bool, InDefaultValue: FString): Bool;
	public function AddModel(InName: FString, bSetupUndoRedo: Bool, bPrintPythonCommand: Bool): ucpp.Ptr<RigVMGraph>;
	public function AddMemberVariable(InName: ucpp.Ref<FName>, InCPPType: FString, bIsPublic: Bool, bIsReadOnly: Bool, InDefaultValue: FString): FName;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward(GetPreviewMesh, GetModel, GetMemberVariables, GetLocalFunctionLibrary, GetDefaultModel, GetControllerByName, GetController, GetAllModels)
@:nativeGen
abstract ConstControlRigBlueprint(ControlRigBlueprint) from ControlRigBlueprint {
	public extern var RigGraphDisplaySettings(get, never): RigGraphDisplaySettings;
	public inline extern function get_RigGraphDisplaySettings(): RigGraphDisplaySettings return this.RigGraphDisplaySettings;
	public extern var HierarchySettings(get, never): RigHierarchySettings;
	public inline extern function get_HierarchySettings(): RigHierarchySettings return this.HierarchySettings;
	public extern var VMRuntimeSettings(get, never): RigVMRuntimeSettings;
	public inline extern function get_VMRuntimeSettings(): RigVMRuntimeSettings return this.VMRuntimeSettings;
	public extern var VMCompileSettings(get, never): RigVMCompileSettings;
	public inline extern function get_VMCompileSettings(): RigVMCompileSettings return this.VMCompileSettings;
	public extern var PythonLogSettings(get, never): ControlRigPythonSettings;
	public inline extern function get_PythonLogSettings(): ControlRigPythonSettings return this.PythonLogSettings;
	public extern var PinToOperandMap(get, never): TMap<FString, RigVMOperand>;
	public inline extern function get_PinToOperandMap(): TMap<FString, RigVMOperand> return this.PinToOperandMap;
	public extern var DrawContainer(get, never): RigVMDrawContainer;
	public inline extern function get_DrawContainer(): RigVMDrawContainer return this.DrawContainer;
	public extern var Influences(get, never): RigInfluenceMapPerEvent;
	public inline extern function get_Influences(): RigInfluenceMapPerEvent return this.Influences;
	public extern var Hierarchy(get, never): ucpp.Ptr<RigHierarchy.ConstRigHierarchy>;
	public inline extern function get_Hierarchy(): ucpp.Ptr<RigHierarchy.ConstRigHierarchy> return this.Hierarchy;
}

@:forward
@:nativeGen
@:native("ControlRigBlueprint*")
abstract ControlRigBlueprintPtr(ucpp.Ptr<ControlRigBlueprint>) from ucpp.Ptr<ControlRigBlueprint> to ucpp.Ptr<ControlRigBlueprint>{
	@:from
	public static extern inline function fromValue(v: ControlRigBlueprint): ControlRigBlueprintPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ControlRigBlueprint {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}