// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UCurveImportFactory")
@:include("Factories/CurveImportFactory.h")
@:structAccess
extern class CurveImportFactory extends Factory {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstCurveImportFactory(CurveImportFactory) from CurveImportFactory {
}