// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDatasmithOptionsBase")
@:include("DatasmithImportOptions.h")
extern class DatasmithOptionsBase extends Object {
}

@:forward()
@:nativeGen
abstract ConstDatasmithOptionsBase(DatasmithOptionsBase) from DatasmithOptionsBase {
}