// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ECameraFocusMethod")
@:include("CineCameraComponent.h")
extern enum ECameraFocusMethod {
	DoNotOverride;
	Manual;
	Tracking;
	Disable;
	MAX;
}