// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorGizmoRegistryCategoryEntry_ConditionalSelection")
@:include("EditorInteractiveGizmoRegistry.h")
extern class EditorGizmoRegistryCategoryEntry_ConditionalSelection extends EditorGizmoRegistryCategoryEntry {
}

@:forward()
@:nativeGen
abstract ConstEditorGizmoRegistryCategoryEntry_ConditionalSelection(EditorGizmoRegistryCategoryEntry_ConditionalSelection) from EditorGizmoRegistryCategoryEntry_ConditionalSelection {
}