// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorGizmoRegistryCategoryEntry_Accessory")
@:include("EditorInteractiveGizmoRegistry.h")
@:structAccess
extern class EditorGizmoRegistryCategoryEntry_Accessory extends EditorGizmoRegistryCategoryEntry_ConditionalSelection {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstEditorGizmoRegistryCategoryEntry_Accessory(EditorGizmoRegistryCategoryEntry_Accessory) from EditorGizmoRegistryCategoryEntry_Accessory {
}