// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EEnvTestFilterOperator.Type")
@:include("EnvironmentQuery/EnvQueryTypes.h")
extern enum EEnvTestFilterOperator {
	AllPass;
	AnyPass;
	EEnvTestFilterOperator_MAX;
}