// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EFoliageScaling")
@:include("FoliageType.h")
extern enum EFoliageScaling {
	Uniform;
	Free;
	LockXY;
	LockXZ;
	LockYZ;
	EFoliageScaling_MAX;
}