// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ELocalizedTextCollapseMode")
@:include("PortableObjectPipeline.h")
extern class ELocalizedTextCollapseMode {
	static var IdenticalTextIdAndSource: ELocalizedTextCollapseMode;
	static var IdenticalPackageIdTextIdAndSource: ELocalizedTextCollapseMode;
	static var IdenticalNamespaceAndSource: ELocalizedTextCollapseMode;
	static var ELocalizedTextCollapseMode_MAX: ELocalizedTextCollapseMode;
}