// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FEmptyPayload")
@:include("Animation/AnimData/AnimDataNotifications.h")
@:valueType
extern class EmptyPayload {
	@:native("FEmptyPayload") public function new();
}