// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ENCPoolMethod")
@:include("NiagaraComponentPoolMethodEnum.h")
extern class ENCPoolMethod {
	static var None: ENCPoolMethod;
	static var AutoRelease: ENCPoolMethod;
	static var ManualRelease: ENCPoolMethod;
	static var ManualRelease_OnComplete: ENCPoolMethod;
	static var FreeInPool: ENCPoolMethod;
	static var ENCPoolMethod_MAX: ENCPoolMethod;
}