// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EPoseDriverOutput")
@:include("AnimNodes/AnimNode_PoseDriver.h")
extern class EPoseDriverOutput {
	static var DrivePoses: EPoseDriverOutput;
	static var DriveCurves: EPoseDriverOutput;
	static var EPoseDriverOutput_MAX: EPoseDriverOutput;
}