// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ERetargetTranslationMode")
@:include("Retargeter/IKRetargetSettings.h")
extern class ERetargetTranslationMode {
	static var None: ERetargetTranslationMode;
	static var GloballyScaled: ERetargetTranslationMode;
	static var Absolute: ERetargetTranslationMode;
	static var ERetargetTranslationMode_MAX: ERetargetTranslationMode;
}