// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAnimNode_BoneDrivenController")
@:include("BoneControllers/AnimNode_BoneDrivenController.h")
extern class FAnimNode_BoneDrivenController extends FAnimNode_SkeletalControlBase {
	public var SourceBone: FBoneReference;
	public var DrivingCurve: TObjectPtr<UCurveFloat>;
	public var Multiplier: cpp.Float32;
	public var RangeMin: cpp.Float32;
	public var RangeMax: cpp.Float32;
	public var RemappedMin: cpp.Float32;
	public var RemappedMax: cpp.Float32;
	public var ParameterName: FName;
	public var TargetBone: FBoneReference;
	public var TargetComponent_DEPRECATED: EComponentType;
	public var DestinationMode: EDrivenDestinationMode;
	public var ModificationMode: EDrivenBoneModificationMode;
	public var SourceComponent: EComponentType;
	public var bUseRange: Bool;
	public var bAffectTargetTranslationX: Bool;
	public var bAffectTargetTranslationY: Bool;
	public var bAffectTargetTranslationZ: Bool;
	public var bAffectTargetRotationX: Bool;
	public var bAffectTargetRotationY: Bool;
	public var bAffectTargetRotationZ: Bool;
	public var bAffectTargetScaleX: Bool;
	public var bAffectTargetScaleY: Bool;
	public var bAffectTargetScaleZ: Bool;
}