// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FChaosDebugSubstepControl")
@:include("Chaos/ChaosSolverActor.h")
extern class FChaosDebugSubstepControl {
	public var bPause: Bool;
	public var bSubstep: Bool;
	public var bStep: Bool;
}