// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FNiagaraCompileEventSource")
@:include("NiagaraShared.h")
extern enum FNiagaraCompileEventSource {
	Unset;
	ScriptDependency;
	FNiagaraCompileEventSource_MAX;
}