// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FPawnActionStack")
@:include("Actions/PawnActionsComponent.h")
extern class FPawnActionStack {
	public var TopAction: TObjectPtr<UPawnAction>;
}