// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FSequencerBoundObjects")
@:include("SequencerTools.h")
extern class FSequencerBoundObjects {
	public var BindingProxy: FSequencerBindingProxy;
	public var BoundObjects: TArray<TObjectPtr<UObject>>;
}