// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FGameplayDebuggerPlayerData")
@:include("GameplayDebuggerPlayerManager.h")
@:valueType
extern class GameplayDebuggerPlayerData {
	public var Controller: ucpp.Ptr<GameplayDebuggerLocalController>;
	public var InputComponent: ucpp.Ptr<InputComp>;
	public var Replicator: ucpp.Ptr<GameplayDebuggerCategoryReplicator>;

	@:native("FGameplayDebuggerPlayerData") public function new();
	@:native("FGameplayDebuggerPlayerData") public static function make(Controller: ucpp.Ptr<GameplayDebuggerLocalController>, InputComponent: ucpp.Ptr<InputComp>, Replicator: ucpp.Ptr<GameplayDebuggerCategoryReplicator>): GameplayDebuggerPlayerData ;
}