// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGeoTrackingAvailabilityDelegate__PythonCallable")
@:structAccess
extern class GeoTrackingAvailabilityDelegate__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstGeoTrackingAvailabilityDelegate__PythonCallable(GeoTrackingAvailabilityDelegate__PythonCallable) from GeoTrackingAvailabilityDelegate__PythonCallable {
}