// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UInputVectorAxisHandlerDynamicSignature__PythonCallable")
@:structAccess
extern class InputVectorAxisHandlerDynamicSignature__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstInputVectorAxisHandlerDynamicSignature__PythonCallable(InputVectorAxisHandlerDynamicSignature__PythonCallable) from InputVectorAxisHandlerDynamicSignature__PythonCallable {
}