// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UInterchangeFactoryBase")
@:include("InterchangeFactoryBase.h")
extern class InterchangeFactoryBase extends Object {
	public var Results: cpp.Star<InterchangeResultsContainer>;

	public function GetFactoryClass(): cpp.Reference<cpp.Star<Class>>;
}

@:forward(GetFactoryClass)
@:nativeGen
abstract ConstInterchangeFactoryBase(InterchangeFactoryBase) from InterchangeFactoryBase {
	public extern var Results(get, never): cpp.Star<InterchangeResultsContainer.ConstInterchangeResultsContainer>;
	public inline extern function get_Results(): cpp.Star<InterchangeResultsContainer.ConstInterchangeResultsContainer> return this.Results;
}