// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UK2Node_CallMaterialParameterCollectionFunction")
@:include("K2Node_CallMaterialParameterCollectionFunction.h")
@:valueType
extern class K2Node_CallMaterialParameterCollectionFunction extends K2Node_CallFunction {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstK2Node_CallMaterialParameterCollectionFunction(K2Node_CallMaterialParameterCollectionFunction) from K2Node_CallMaterialParameterCollectionFunction {
}

@:forward
@:nativeGen
@:native("K2Node_CallMaterialParameterCollectionFunction*")
abstract K2Node_CallMaterialParameterCollectionFunctionPtr(ucpp.Ptr<K2Node_CallMaterialParameterCollectionFunction>) from ucpp.Ptr<K2Node_CallMaterialParameterCollectionFunction> to ucpp.Ptr<K2Node_CallMaterialParameterCollectionFunction>{
	@:from
	public static extern inline function fromValue(v: K2Node_CallMaterialParameterCollectionFunction): K2Node_CallMaterialParameterCollectionFunctionPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): K2Node_CallMaterialParameterCollectionFunction {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}