// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ULandscapeGizmoRenderComponent")
@:include("LandscapeGizmoRenderComponent.h")
@:valueType
extern class LandscapeGizmoRenderComp extends PrimitiveComp {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstLandscapeGizmoRenderComp(LandscapeGizmoRenderComp) from LandscapeGizmoRenderComp {
}

@:forward
@:nativeGen
@:native("LandscapeGizmoRenderComp*")
abstract LandscapeGizmoRenderCompPtr(ucpp.Ptr<LandscapeGizmoRenderComp>) from ucpp.Ptr<LandscapeGizmoRenderComp> to ucpp.Ptr<LandscapeGizmoRenderComp>{
	@:from
	public static extern inline function fromValue(v: LandscapeGizmoRenderComp): LandscapeGizmoRenderCompPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): LandscapeGizmoRenderComp {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}