// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FLevelSequenceBindingReferences")
@:include("LevelSequenceBindingReference.h")
@:valueType
extern class LevelSequenceBindingReferences {
	private var BindingIdToReferences: TMap<Guid, LevelSequenceBindingReferenceArray>;
	private var AnimSequenceInstances: TSet<Guid>;
	private var PostProcessInstances: TSet<Guid>;

	@:native("FLevelSequenceBindingReferences") public function new();
	@:native("FLevelSequenceBindingReferences") public static function make(BindingIdToReferences: TMap<Guid, LevelSequenceBindingReferenceArray>, AnimSequenceInstances: TSet<Guid>, PostProcessInstances: TSet<Guid>): LevelSequenceBindingReferences ;
}