// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionConstant2Vector")
@:include("Materials/MaterialExpressionConstant2Vector.h")
@:structAccess
extern class MaterialExpressionConstant2Vector extends MaterialExpression {
	public var R: cpp.Float32;
	public var G: cpp.Float32;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMaterialExpressionConstant2Vector(MaterialExpressionConstant2Vector) from MaterialExpressionConstant2Vector {
	public extern var R(get, never): cpp.Float32;
	public inline extern function get_R(): cpp.Float32 return this.R;
	public extern var G(get, never): cpp.Float32;
	public inline extern function get_G(): cpp.Float32 return this.G;
}