// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMeshCommandChangeTarget")
extern class MeshCommandChangeTarget extends Interface {
}

@:forward()
@:nativeGen
abstract ConstMeshCommandChangeTarget(MeshCommandChangeTarget) from MeshCommandChangeTarget {
}