// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneValueDecomposer")
@:structAccess
extern class MovieSceneValueDecomposer extends Interface {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieSceneValueDecomposer(MovieSceneValueDecomposer) from MovieSceneValueDecomposer {
}