// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieScene3DTransformTrack")
@:include("Tracks/MovieScene3DTransformTrack.h")
@:valueType
extern class MovieScene3DTransformTrack extends MovieScenePropertyTrack {
	private var BlenderSystemClass: TSubclassOf<MovieSceneBlenderSystem>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieScene3DTransformTrack(MovieScene3DTransformTrack) from MovieScene3DTransformTrack {
}

@:forward
@:nativeGen
@:native("MovieScene3DTransformTrack*")
abstract MovieScene3DTransformTrackPtr(ucpp.Ptr<MovieScene3DTransformTrack>) from ucpp.Ptr<MovieScene3DTransformTrack> to ucpp.Ptr<MovieScene3DTransformTrack>{
	@:from
	public static extern inline function fromValue(v: MovieScene3DTransformTrack): MovieScene3DTransformTrackPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MovieScene3DTransformTrack {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}