// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMovieSceneFrameRange")
@:include("MovieSceneFrameMigration.h")
@:valueType
extern class MovieSceneFrameRange {
	@:native("FMovieSceneFrameRange") public function new();
}