// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneScriptingObjectPathKey")
@:include("KeysAndChannels/MovieSceneScriptingObjectPath.h")
extern class MovieSceneScriptingObjectPathKey extends MovieSceneScriptingKey {
	public function SetValue(InNewValue: cpp.Star<Object>): Void;
	public function SetTime(NewFrameNumber: cpp.Reference<FrameNumber>, SubFrame: cpp.Float32, TimeUnit: ESequenceTimeUnit): Void;
	public function GetValue(): cpp.Reference<cpp.Star<Object>>;
	public function GetTime(TimeUnit: ESequenceTimeUnit): cpp.Reference<FrameTime>;
}

@:forward(GetValue, GetTime)
@:nativeGen
abstract ConstMovieSceneScriptingObjectPathKey(MovieSceneScriptingObjectPathKey) from MovieSceneScriptingObjectPathKey {
}