// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneBindingOwnerInterface")
@:structAccess
extern class MovieSceneBindingOwnerInterface extends Interface {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieSceneBindingOwnerInterface(MovieSceneBindingOwnerInterface) from MovieSceneBindingOwnerInterface {
}