// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FNiagaraDeviceProfileStateEntry")
@:include("NiagaraPlatformSet.h")
@:valueType
extern class NiagaraDeviceProfileStateEntry {
	public var ProfileName: FName;
	public var QualityLevelMask: ucpp.num.UInt32;
	public var SetQualityLevelMask: ucpp.num.UInt32;

	@:native("FNiagaraDeviceProfileStateEntry") public function new();
	@:native("FNiagaraDeviceProfileStateEntry") public static function make(ProfileName: FName, QualityLevelMask: ucpp.num.UInt32, SetQualityLevelMask: ucpp.num.UInt32): NiagaraDeviceProfileStateEntry ;
}