// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraDataInterfaceAudioOscilloscope")
@:include("NiagaraDataInterfaceAudioOscilloscope.h")
extern class NiagaraDataInterfaceAudioOscilloscope extends NiagaraDataInterface {
	public var Submix: cpp.Star<SoundSubmix>;
	public var Resolution: cpp.Int32;
	public var ScopeInMilliseconds: cpp.Float32;
}

@:forward()
@:nativeGen
abstract ConstNiagaraDataInterfaceAudioOscilloscope(NiagaraDataInterfaceAudioOscilloscope) from NiagaraDataInterfaceAudioOscilloscope {
	public extern var Submix(get, never): cpp.Star<SoundSubmix.ConstSoundSubmix>;
	public inline extern function get_Submix(): cpp.Star<SoundSubmix.ConstSoundSubmix> return this.Submix;
	public extern var Resolution(get, never): cpp.Int32;
	public inline extern function get_Resolution(): cpp.Int32 return this.Resolution;
	public extern var ScopeInMilliseconds(get, never): cpp.Float32;
	public inline extern function get_ScopeInMilliseconds(): cpp.Float32 return this.ScopeInMilliseconds;
}