// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnEditPasteActorsEnd__PythonCallable")
@:structAccess
extern class OnEditPasteActorsEnd__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstOnEditPasteActorsEnd__PythonCallable(OnEditPasteActorsEnd__PythonCallable) from OnEditPasteActorsEnd__PythonCallable {
}