// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnItemIsHoveredChangedDynamic__PythonCallable")
@:valueType
extern class OnItemIsHoveredChangedDynamic__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstOnItemIsHoveredChangedDynamic__PythonCallable(OnItemIsHoveredChangedDynamic__PythonCallable) from OnItemIsHoveredChangedDynamic__PythonCallable {
}

@:forward
@:nativeGen
@:native("OnItemIsHoveredChangedDynamic__PythonCallable*")
abstract OnItemIsHoveredChangedDynamic__PythonCallablePtr(ucpp.Ptr<OnItemIsHoveredChangedDynamic__PythonCallable>) from ucpp.Ptr<OnItemIsHoveredChangedDynamic__PythonCallable> to ucpp.Ptr<OnItemIsHoveredChangedDynamic__PythonCallable>{
	@:from
	public static extern inline function fromValue(v: OnItemIsHoveredChangedDynamic__PythonCallable): OnItemIsHoveredChangedDynamic__PythonCallablePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): OnItemIsHoveredChangedDynamic__PythonCallable {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}