// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnlineBlueprintCallProxyBase")
@:include("Net/OnlineBlueprintCallProxyBase.h")
extern class OnlineBlueprintCallProxyBase extends BlueprintAsyncActionBase {
}

@:forward()
@:nativeGen
abstract ConstOnlineBlueprintCallProxyBase(OnlineBlueprintCallProxyBase) from OnlineBlueprintCallProxyBase {
}