// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnPerChannelLoudnessResults__PythonCallable")
@:structAccess
extern class OnPerChannelLoudnessResults__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstOnPerChannelLoudnessResults__PythonCallable(OnPerChannelLoudnessResults__PythonCallable) from OnPerChannelLoudnessResults__PythonCallable {
}