// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UParticleModuleAttractorPointGravity")
@:include("Particles/Attractor/ParticleModuleAttractorPointGravity.h")
@:valueType
extern class ParticleModuleAttractorPointGravity extends ParticleModuleAttractorBase {
	public var Position: Vector;
	public var Radius: ucpp.num.Float32;
	public var StrengthRaw: RawDistributionFloat;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstParticleModuleAttractorPointGravity(ParticleModuleAttractorPointGravity) from ParticleModuleAttractorPointGravity {
	public extern var Position(get, never): Vector;
	public inline extern function get_Position(): Vector return this.Position;
	public extern var Radius(get, never): ucpp.num.Float32;
	public inline extern function get_Radius(): ucpp.num.Float32 return this.Radius;
	public extern var StrengthRaw(get, never): RawDistributionFloat;
	public inline extern function get_StrengthRaw(): RawDistributionFloat return this.StrengthRaw;
}

@:forward
@:nativeGen
@:native("ParticleModuleAttractorPointGravity*")
abstract ParticleModuleAttractorPointGravityPtr(ucpp.Ptr<ParticleModuleAttractorPointGravity>) from ucpp.Ptr<ParticleModuleAttractorPointGravity> to ucpp.Ptr<ParticleModuleAttractorPointGravity>{
	@:from
	public static extern inline function fromValue(v: ParticleModuleAttractorPointGravity): ParticleModuleAttractorPointGravityPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ParticleModuleAttractorPointGravity {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}