// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UParticleModuleRotation")
@:include("Particles/Rotation/ParticleModuleRotation.h")
@:structAccess
extern class ParticleModuleRotation extends ParticleModuleRotationBase {
	public var StartRotation: RawDistributionFloat;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstParticleModuleRotation(ParticleModuleRotation) from ParticleModuleRotation {
	public extern var StartRotation(get, never): RawDistributionFloat;
	public inline extern function get_StartRotation(): RawDistributionFloat return this.StartRotation;
}