// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FPBIKEffector")
@:include("RigUnit_PBIK.h")
@:valueType
extern class PBIKEffector {
	public var Bone: FName;
	public var Transform: Transform;
	public var PositionAlpha: ucpp.num.Float32;
	public var RotationAlpha: ucpp.num.Float32;
	public var StrengthAlpha: ucpp.num.Float32;
	public var PullChainAlpha: ucpp.num.Float32;
	public var PinRotation: ucpp.num.Float32;

	@:native("FPBIKEffector") public function new();
}