// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPluginClassTemplate")
@:include("ClassTemplateEditorSubsystem.h")
@:structAccess
extern class PluginClassTemplate extends ClassTemplate {
	public var PluginName: FString;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstPluginClassTemplate(PluginClassTemplate) from PluginClassTemplate {
	public extern var PluginName(get, never): FString;
	public inline extern function get_PluginName(): FString return this.PluginName;
}