// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPreviewMesh")
@:include("PreviewMesh.h")
extern class PreviewMesh extends Object {
	public var bBuildSpatialDataStructure: Bool;
	public var DynamicMeshComponent: cpp.Star<DynamicMeshComp>;
}

@:forward()
@:nativeGen
abstract ConstPreviewMesh(PreviewMesh) from PreviewMesh {
	public extern var bBuildSpatialDataStructure(get, never): Bool;
	public inline extern function get_bBuildSpatialDataStructure(): Bool return this.bBuildSpatialDataStructure;
	public extern var DynamicMeshComponent(get, never): cpp.Star<DynamicMeshComp.ConstDynamicMeshComp>;
	public inline extern function get_DynamicMeshComponent(): cpp.Star<DynamicMeshComp.ConstDynamicMeshComp> return this.DynamicMeshComponent;
}