// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPrimitiveComponentToolTarget")
@:include("ToolTargets/PrimitiveComponentToolTarget.h")
@:structAccess
extern class PrimitiveComponentToolTarget extends ToolTarget {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstPrimitiveComponentToolTarget(PrimitiveComponentToolTarget) from PrimitiveComponentToolTarget {
}