// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UStaticMeshDescriptionBulkData")
@:include("Engine/StaticMeshSourceData.h")
@:valueType
extern class StaticMeshDescriptionBulkData extends MeshDescriptionBaseBulkData {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstStaticMeshDescriptionBulkData(StaticMeshDescriptionBulkData) from StaticMeshDescriptionBulkData {
}

@:forward
@:nativeGen
@:native("StaticMeshDescriptionBulkData*")
abstract StaticMeshDescriptionBulkDataPtr(ucpp.Ptr<StaticMeshDescriptionBulkData>) from ucpp.Ptr<StaticMeshDescriptionBulkData> to ucpp.Ptr<StaticMeshDescriptionBulkData>{
	@:from
	public static extern inline function fromValue(v: StaticMeshDescriptionBulkData): StaticMeshDescriptionBulkDataPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): StaticMeshDescriptionBulkData {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}