// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UActorBeginCursorOverSignature__PythonCallable")
extern class UActorBeginCursorOverSignature__PythonCallable extends UPythonCallableForDelegate {
}
