// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UActorFactoryVolumetricCloud")
@:include("ActorFactories/ActorFactoryVolumetricCloud.h")
extern class UActorFactoryVolumetricCloud extends UActorFactory {
}
