// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAISenseEvent_Hearing")
@:include("Perception/AISenseEvent_Hearing.h")
extern class UAISenseEvent_Hearing extends UAISenseEvent {
	public var Event: FAINoiseEvent;
}
