// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimDataModel")
@:include("Animation/AnimData/AnimDataModel.h")
extern class UAnimDataModel extends UObject {
	public var BracketCounter: cpp.Int32;
	public var ModifiedEventDynamic: HaxeMulticastSparseDelegateProperty<(EAnimDataModelNotifyType, cpp.Star<UAnimDataModel>, FAnimDataModelNotifPayload) -> Void>;
	public var BoneAnimationTracks: TArray<FBoneAnimationTrack>;
	public var PlayLength: cpp.Float32;
	public var FrameRate: FFrameRate;
	public var NumberOfFrames: cpp.Int32;
	public var NumberOfKeys: cpp.Int32;
	public var CurveData: FAnimationCurveData;
	public var AnimatedBoneAttributes: TArray<FAnimatedBoneAttribute>;
	public var RawAnimationTracks: TArray<FRawAnimSequenceTrack>;
	public var RawAnimationTrackNames: TArray<FName>;
	public var RawAnimationTrackSkeletonMappings: TArray<FTrackToSkeletonMap>;
	public var RawCurveTracks: FRawCurveTracks;

	public function IsValidBoneTrackIndex(TrackIndex: cpp.Int32): Bool;
	public function GetPlayLength(): cpp.Float32;
	public function GetNumBoneTracks(): cpp.Int32;
	public function GetNumberOfTransformCurves(): cpp.Int32;
	public function GetNumberOfKeys(): cpp.Int32;
	public function GetNumberOfFrames(): cpp.Int32;
	public function GetNumberOfFloatCurves(): cpp.Int32;
	public function GetFrameRate(): FFrameRate;
	public function GetBoneTrackNames(OutNames: TArray<FName>): Void;
	public function GetBoneTrackIndexByName(TrackName: FName): cpp.Int32;
	public function GetBoneTrackIndex(Track: FBoneAnimationTrack): cpp.Int32;
	public function GetBoneTrackByName(TrackName: FName): FBoneAnimationTrack;
	public function GetBoneTrackByIndex(TrackIndex: cpp.Int32): FBoneAnimationTrack;
	public function GetBoneAnimationTracks(): TArray<FBoneAnimationTrack>;
	public function GetAnimationSequence(): cpp.Star<UAnimSequence>;
}
