// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAssetTools")
extern class UAssetTools extends UInterface {

	public function RenameReferencingSoftObjectPaths(PackagesToCheck: TArray<cpp.Star<UPackage>>, AssetRedirectorMap: TMap<FSoftObjectPath, FSoftObjectPath>): Void;
	public function RenameAssetsWithDialog(AssetsAndNames: TArray<FAssetRenameData>, bAutoCheckout: Bool): EAssetRenameResult;
	public function RenameAssets(AssetsAndNames: TArray<FAssetRenameData>): Bool;
	public function OpenEditorForAssets(Assets: TArray<cpp.Star<UObject>>): Void;
	public function ImportAssetTasks(ImportTasks: TArray<cpp.Star<UAssetImportTask>>): Void;
	public function ImportAssetsWithDialog(DestinationPath: FString): TArray<cpp.Star<UObject>>;
	public function ImportAssetsAutomated(ImportData: cpp.Star<UAutomatedAssetImportData>): TArray<cpp.Star<UObject>>;
	public function FindSoftReferencesToObject(TargetObject: FSoftObjectPath, ReferencingObjects: TArray<cpp.Star<UObject>>): Void;
	public function ExportAssetsWithDialog(AssetsToExport: TArray<FString>, bPromptForIndividualFilenames: Bool): Void;
	public function ExportAssets(AssetsToExport: TArray<FString>, ExportPath: FString): Void;
	public function DuplicateAssetWithDialogAndTitle(AssetName: FString, PackagePath: FString, OriginalObject: cpp.Star<UObject>, DialogTitle: FText): cpp.Star<UObject>;
	public function DuplicateAssetWithDialog(AssetName: FString, PackagePath: FString, OriginalObject: cpp.Star<UObject>): cpp.Star<UObject>;
	public function DuplicateAsset(AssetName: FString, PackagePath: FString, OriginalObject: cpp.Star<UObject>): cpp.Star<UObject>;
	public function CreateUniqueAssetName(InBasePackageName: FString, InSuffix: FString, OutPackageName: cpp.Reference<FString>, OutAssetName: cpp.Reference<FString>): Void;
	public function CreateAssetWithDialog(AssetName: FString, PackagePath: FString, AssetClass: cpp.Star<UClass>, Factory: cpp.Star<UFactory>, CallingContext: FName, bCallConfigureProperties: Bool): cpp.Star<UObject>;
	public function CreateAsset(AssetName: FString, PackagePath: FString, AssetClass: cpp.Star<UClass>, Factory: cpp.Star<UFactory>, CallingContext: FName): cpp.Star<UObject>;
}
