// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAutomationUtilsBlueprintLibrary")
@:include("AutomationUtilsBlueprintLibrary.h")
extern class UAutomationUtilsBlueprintLibrary extends UBlueprintFunctionLibrary {

	public function TakeGameplayAutomationScreenshot(ScreenshotName: FString, MaxGlobalError: cpp.Float32, MaxLocalError: cpp.Float32, MapNameOverride: FString): Void;
}
