// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlackboardKeyType_String")
@:include("BehaviorTree/Blackboard/BlackboardKeyType_String.h")
extern class UBlackboardKeyType_String extends UBlackboardKeyType {
	public var StringValue: FString;
}
