// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlendSpaceFactoryNew")
@:include("Factories/BlendSpaceFactoryNew.h")
extern class UBlendSpaceFactoryNew extends UFactory {
	public var TargetSkeleton: TObjectPtr<USkeleton>;
	public var PreviewSkeletalMesh: TObjectPtr<USkeletalMesh>;
}
