// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBlueprintDelegateNodeSpawner")
@:include("BlueprintDelegateNodeSpawner.h")
extern class UBlueprintDelegateNodeSpawner extends UBlueprintFieldNodeSpawner {
}
