// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UClothingSimulationInteractor")
@:include("ClothingSimulationInteractor.h")
extern class UClothingSimulationInteractor extends UObject {
	public var ClothingInteractors: TMap<FName, TObjectPtr<UClothingInteractor>>;

	public function SetNumSubsteps(NumSubsteps: cpp.Int32): Void;
	public function SetNumIterations(NumIterations: cpp.Int32): Void;
	public function SetMaxNumIterations(MaxNumIterations: cpp.Int32): Void;
	public function SetAnimDriveSpringStiffness(InStiffness: cpp.Float32): Void;
	public function PhysicsAssetUpdated(): Void;
	public function GetSimulationTime(): cpp.Float32;
	public function GetNumSubsteps(): cpp.Int32;
	public function GetNumKinematicParticles(): cpp.Int32;
	public function GetNumIterations(): cpp.Int32;
	public function GetNumDynamicParticles(): cpp.Int32;
	public function GetNumCloths(): cpp.Int32;
	public function GetClothingInteractor(ClothingAssetName: FString): cpp.Star<UClothingInteractor>;
	public function EnableGravityOverride(InVector: FVector): Void;
	public function DisableGravityOverride(): Void;
	public function ClothConfigUpdated(): Void;
}
