// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UControlRigPoseProjectSettings")
@:include("Tools/ControlRigPoseProjectSettings.h")
extern class UControlRigPoseProjectSettings extends UObject {
	public var RootSaveDirs: TArray<FDirectoryPath>;
}
