// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDialogueSoundWaveProxy")
@:include("Sound/DialogueSoundWaveProxy.h")
extern class UDialogueSoundWaveProxy extends USoundBase {
}
