// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorWorldExtension")
@:include("EditorWorldExtension.h")
extern class UEditorWorldExtension extends UObject {
	public var ExtensionActors: TArray<FEditorWorldExtensionActorData>;
}
