// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UFontImportOptions")
@:include("Engine/FontImportOptions.h")
extern class UFontImportOptions extends UObject {
	public var Data: FFontImportOptionsData;
}
