// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UK2Node_EaseFunction")
@:include("K2Node_EaseFunction.h")
extern class UK2Node_EaseFunction extends UK2Node {
	public var EaseFunctionName: FName;
}
