// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionTangentOutput")
@:include("Materials/MaterialExpressionTangentOutput.h")
extern class UMaterialExpressionTangentOutput extends UMaterialExpressionCustomOutput {
	public var Input: FExpressionInput;
}
