// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionStrataAdd")
@:include("Materials/MaterialExpressionStrata.h")
extern class UMaterialExpressionStrataAdd extends UMaterialExpressionStrataBSDF {
	public var A: FExpressionInput;
	public var B: FExpressionInput;
	public var bUseParameterBlending: Bool;
}
