// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMediaPlaylist")
@:include("MediaPlaylist.h")
extern class UMediaPlaylist extends UObject {
	public var Items: TArray<TObjectPtr<UMediaSource>>;

	public function Replace(Index: cpp.Int32, Replacement: cpp.Star<UMediaSource>): Bool;
	public function RemoveAt(Index: cpp.Int32): Bool;
	public function Remove(MediaSource: cpp.Star<UMediaSource>): Bool;
	public function Num(): cpp.Int32;
	public function Insert(MediaSource: cpp.Star<UMediaSource>, Index: cpp.Int32): Void;
	public function GetRandom(OutIndex: cpp.Reference<cpp.Int32>): cpp.Star<UMediaSource>;
	public function GetPrevious(InOutIndex: cpp.Reference<cpp.Int32>): cpp.Star<UMediaSource>;
	public function GetNext(InOutIndex: cpp.Reference<cpp.Int32>): cpp.Star<UMediaSource>;
	public function Get(Index: cpp.Int32): cpp.Star<UMediaSource>;
	public function AddUrl(Url: FString): Bool;
	public function AddFile(FilePath: FString): Bool;
	public function Add(MediaSource: cpp.Star<UMediaSource>): Bool;
}
