// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneScriptingActualFloatKey")
@:include("KeysAndChannels/MovieSceneScriptingFloat.h")
extern class UMovieSceneScriptingActualFloatKey extends UMovieSceneScriptingFloatKey {
}
