// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneCopyableBinding")
@:include("MovieSceneCopyableBinding.h")
extern class UMovieSceneCopyableBinding extends UObject {
	public var SpawnableObjectTemplate: TObjectPtr<UObject>;
	public var Tracks: TArray<TObjectPtr<UMovieSceneTrack>>;
	public var Binding: FMovieSceneBinding;
	public var Spawnable: FMovieSceneSpawnable;
	public var Possessable: FMovieScenePossessable;
	public var FolderPath: TArray<FName>;
}
