// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneNameableTrack")
@:include("MovieSceneNameableTrack.h")
extern class UMovieSceneNameableTrack extends UMovieSceneTrack {
	public var DisplayName: FText;
	public var TrackRowDisplayNames: TArray<FText>;
}
