// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieScene3DAttachTrack")
@:include("Tracks/MovieScene3DAttachTrack.h")
extern class UMovieScene3DAttachTrack extends UMovieScene3DConstraintTrack {
}
