// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneCaptureEnvironment")
@:include("MovieSceneCaptureEnvironment.h")
extern class UMovieSceneCaptureEnvironment extends UObject {

	public function IsCaptureInProgress(): Bool;
	public function GetCaptureFrameNumber(): cpp.Int32;
	public function GetCaptureElapsedTime(): cpp.Float32;
	public function FindImageCaptureProtocol(): cpp.Star<UMovieSceneImageCaptureProtocolBase>;
	public function FindAudioCaptureProtocol(): cpp.Star<UMovieSceneAudioCaptureProtocolBase>;
}
