// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieScenePiecewiseDoubleBlenderSystem")
@:include("Systems/MovieScenePiecewiseDoubleBlenderSystem.h")
extern class UMovieScenePiecewiseDoubleBlenderSystem extends UMovieSceneBlenderSystem {
}
