// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraStackEditorData")
@:include("NiagaraStackEditorData.h")
extern class UNiagaraStackEditorData extends UNiagaraEditorDataBase {
	public var StackEntryKeyToExpandedMap: TMap<FString, Bool>;
	public var StackEntryKeyToExpandedOverviewMap: TMap<FString, Bool>;
	public var StackEntryKeyToDisplayName: TMap<FString, FText>;
	public var DismissedStackIssueIds: TArray<FString>;
}
