// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraDataInterfaceActorComponent")
@:include("DataInterface/NiagaraDataInterfaceActorComponent.h")
extern class UNiagaraDataInterfaceActorComponent extends UNiagaraDataInterface {
	public var bRequireCurrentFrameData: Bool;
	public var SourceActor: TLazyObjectPtr<AActor>;
	public var ActorOrComponentParameter: FNiagaraUserParameterBinding;
}
