// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UUniformScaleDragOperation")
@:include("ViewportInteractionDragOperations.h")
extern class UniformScaleDragOperation extends ViewportDragOperation {
}

@:forward()
@:nativeGen
abstract ConstUniformScaleDragOperation(UniformScaleDragOperation) from UniformScaleDragOperation {
}