// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnAssetReimport_Dyn__PythonCallable")
extern class UOnAssetReimport_Dyn__PythonCallable extends UPythonCallableForDelegate {
}
