// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnCanvasRenderTargetUpdate__PythonCallable")
extern class UOnCanvasRenderTargetUpdate__PythonCallable extends UPythonCallableForDelegate {
}
