// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnlineSession")
@:include("GameFramework/OnlineSession.h")
extern class UOnlineSession extends UObject {
}
