// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPawnAction_Sequence")
@:include("Actions/PawnAction_Sequence.h")
extern class UPawnAction_Sequence extends UPawnAction {
	public var ActionSequence: TArray<TObjectPtr<UPawnAction>>;
	public var ChildFailureHandlingMode: EPawnActionFailHandling;
	public var RecentActionCopy: TObjectPtr<UPawnAction>;
}
