// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPostEvaluateAnimEvent__PythonCallable")
extern class UPostEvaluateAnimEvent__PythonCallable extends UPythonCallableForDelegate {
}
