// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UProceduralTorusToolProperties")
@:include("AddPrimitiveTool.h")
extern class UProceduralTorusToolProperties extends UProceduralShapeToolProperties {
	public var MajorRadius: cpp.Float32;
	public var MinorRadius: cpp.Float32;
	public var MajorSlices: cpp.Int32;
	public var MinorSlices: cpp.Int32;
}
