// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UResonanceAudioSpatializationSourceSettings")
@:include("ResonanceAudioSpatializationSourceSettings.h")
extern class UResonanceAudioSpatializationSourceSettings extends USpatializationPluginSourceSettingsBase {
	public var SpatializationMethod: ERaSpatializationMethod;
	public var Pattern: cpp.Float32;
	public var Sharpness: cpp.Float32;
	public var bToggleVisualization: Bool;
	public var Scale: cpp.Float32;
	public var Spread: cpp.Float32;
	public var Rolloff: ERaDistanceRolloffModel;
	public var MinDistance: cpp.Float32;
	public var MaxDistance: cpp.Float32;

	public function SetSoundSourceSpread(InSpread: cpp.Float32): Void;
	public function SetSoundSourceDirectivity(InPattern: cpp.Float32, InSharpness: cpp.Float32): Void;
}
