// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USafeZone")
@:include("Components/SafeZone.h")
extern class USafeZone extends UContentWidget {
	public var PadLeft: Bool;
	public var PadRight: Bool;
	public var PadTop: Bool;
	public var PadBottom: Bool;

	public function SetSidesToPad(InPadLeft: Bool, InPadRight: Bool, InPadTop: Bool, InPadBottom: Bool): Void;
}
