// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USoundSourceEffectFactory")
@:include("Factories/SoundSourceEffectFactory.h")
extern class USoundSourceEffectFactory extends UFactory {
	public var SoundEffectSourcepresetClass: TSubclassOf<USoundEffectSourcePreset>;
}
