// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UToolTargetFactory")
@:include("ToolTargets/ToolTarget.h")
extern class UToolTargetFactory extends UObject {
}
