// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UUnrealPakCommandlet")
@:include("Commandlets/UnrealPakCommandlet.h")
extern class UUnrealPakCommandlet extends UCommandlet {
}
