// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UViewport")
@:include("Components/Viewport.h")
extern class UViewport extends UContentWidget {
	public var BackgroundColor: FLinearColor;

	public function Spawn(ActorClass: TSubclassOf<AActor>): cpp.Star<AActor>;
	public function SetViewRotation(Rotation: FRotator): Void;
	public function SetViewLocation(Location: FVector): Void;
	public function GetViewRotation(): FRotator;
	public function GetViewportWorld(): cpp.Star<UWorld>;
	public function GetViewLocation(): FVector;
}
