// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWorkPlaneProperties")
@:include("Sculpting/MeshSculptToolBase.h")
extern class UWorkPlaneProperties extends UInteractiveToolPropertySet {
	public var bPropertySetEnabled: Bool;
	public var bShowGizmo: Bool;
	public var Position: FVector;
	public var Rotation: FQuat;
}
