// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FWeightmapLayerAllocationInfo")
@:include("LandscapeComponent.h")
@:valueType
extern class WeightmapLayerAllocationInfo {
	public var LayerInfo: ucpp.Ptr<LandscapeLayerInfoObject>;
	public var WeightmapTextureIndex: ucpp.num.UInt8;
	public var WeightmapTextureChannel: ucpp.num.UInt8;

	@:native("FWeightmapLayerAllocationInfo") public function new();
	@:native("FWeightmapLayerAllocationInfo") public static function make(LayerInfo: ucpp.Ptr<LandscapeLayerInfoObject>, WeightmapTextureIndex: ucpp.num.UInt8, WeightmapTextureChannel: ucpp.num.UInt8): WeightmapLayerAllocationInfo ;
}