// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWorldFactory")
@:include("Factories/WorldFactory.h")
@:structAccess
extern class WorldFactory extends Factory {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstWorldFactory(WorldFactory) from WorldFactory {
}