// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAdvancedCopyCustomization")
@:include("AdvancedCopyCustomization.h")
@:structAccess
extern class AdvancedCopyCustomization extends Object {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstAdvancedCopyCustomization(AdvancedCopyCustomization) from AdvancedCopyCustomization {
}