// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AExponentialHeightFog")
@:include("Engine/ExponentialHeightFog.h")
extern class AExponentialHeightFog extends AInfo {
	public var Component: TObjectPtr<UExponentialHeightFogComponent>;
	public var bEnabled: Bool;

	public function OnRep_bEnabled(): Void;
}
