// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimStateEntryNode")
@:include("AnimStateEntryNode.h")
@:structAccess
extern class AnimStateEntryNode extends EdGraphNode {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstAnimStateEntryNode(AnimStateEntryNode) from AnimStateEntryNode {
}