// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimationStateMachineGraph")
@:include("AnimationStateMachineGraph.h")
@:structAccess
extern class AnimationStateMachineGraph extends EdGraph {
	public var EntryNode: cpp.Star<AnimStateEntryNode>;
	public var OwnerAnimGraphNode: cpp.Star<AnimGraphNode_StateMachineBase>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstAnimationStateMachineGraph(AnimationStateMachineGraph) from AnimationStateMachineGraph {
	public extern var EntryNode(get, never): cpp.Star<AnimStateEntryNode.ConstAnimStateEntryNode>;
	public inline extern function get_EntryNode(): cpp.Star<AnimStateEntryNode.ConstAnimStateEntryNode> return this.EntryNode;
	public extern var OwnerAnimGraphNode(get, never): cpp.Star<AnimGraphNode_StateMachineBase.ConstAnimGraphNode_StateMachineBase>;
	public inline extern function get_OwnerAnimGraphNode(): cpp.Star<AnimGraphNode_StateMachineBase.ConstAnimGraphNode_StateMachineBase> return this.OwnerAnimGraphNode;
}