// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimLayerInterface")
extern class AnimLayerInterface extends Interface {
}

@:forward()
@:nativeGen
abstract ConstAnimLayerInterface(AnimLayerInterface) from AnimLayerInterface {
}