// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("APrecomputedVisibilityVolume")
@:include("Lightmass/PrecomputedVisibilityVolume.h")
extern class APrecomputedVisibilityVolume extends AVolume {
}
