// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FARCameraIntrinsics")
@:include("ARTypes.h")
extern class ARCameraIntrinsics {
	public var ImageResolution: IntPoint;
	public var FocalLength: Vector2D;
	public var PrincipalPoint: Vector2D;
}