// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UArrayProperty")
@:structAccess
extern class ArrayProperty extends Property {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstArrayProperty(ArrayProperty) from ArrayProperty {
}