// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ATriggerSphere")
@:include("Engine/TriggerSphere.h")
extern class ATriggerSphere extends ATriggerBase {
}
