// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAutoCompleteCommand")
@:include("ConsoleSettings.h")
extern class AutoCompleteCommand {
	public var Command: FString;
	public var Desc: FString;
}