// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBTTask_MoveDirectlyToward")
@:include("BehaviorTree/Tasks/BTTask_MoveDirectlyToward.h")
@:structAccess
extern class BTTask_MoveDirectlyToward extends BTTask_MoveTo {
	public var bDisablePathUpdateOnGoalLocationChange: Bool;
	public var bProjectVectorGoalToNavigation: Bool;
	public var bUpdatedDeprecatedProperties: Bool;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstBTTask_MoveDirectlyToward(BTTask_MoveDirectlyToward) from BTTask_MoveDirectlyToward {
	public extern var bDisablePathUpdateOnGoalLocationChange(get, never): Bool;
	public inline extern function get_bDisablePathUpdateOnGoalLocationChange(): Bool return this.bDisablePathUpdateOnGoalLocationChange;
	public extern var bProjectVectorGoalToNavigation(get, never): Bool;
	public inline extern function get_bProjectVectorGoalToNavigation(): Bool return this.bProjectVectorGoalToNavigation;
	public extern var bUpdatedDeprecatedProperties(get, never): Bool;
	public inline extern function get_bUpdatedDeprecatedProperties(): Bool return this.bUpdatedDeprecatedProperties;
}