// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FBuildPromotionImportWorkflowSettings")
@:include("Tests/AutomationTestSettings.h")
extern class BuildPromotionImportWorkflowSettings {
	public var Diffuse: EditorImportWorkflowDefinition;
	public var Normal: EditorImportWorkflowDefinition;
	public var StaticMesh: EditorImportWorkflowDefinition;
	public var ReimportStaticMesh: EditorImportWorkflowDefinition;
	public var BlendShapeMesh: EditorImportWorkflowDefinition;
	public var MorphMesh: EditorImportWorkflowDefinition;
	public var SkeletalMesh: EditorImportWorkflowDefinition;
	public var Animation: EditorImportWorkflowDefinition;
	public var Sound: EditorImportWorkflowDefinition;
	public var SurroundSound: EditorImportWorkflowDefinition;
	public var OtherAssetsToImport: TArray<EditorImportWorkflowDefinition>;
}