// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UCableComponent")
@:include("CableComponent.h")
extern class CableCompComp extends MeshCompoComp {
	public var bAttachStart: Bool;
	public var bAttachEnd: Bool;
	public var AttachEndTo: FComponentReference;
	public var AttachEndToSocketName: FName;
	public var EndLocation: FVector;
	public var CableLength: cpp.Float32;
	public var NumSegments: cpp.Int32;
	public var SubstepTime: cpp.Float32;
	public var SolverIterations: cpp.Int32;
	public var bEnableStiffness: Bool;
	public var bUseSubstepping: Bool;
	public var bSkipCableUpdateWhenNotVisible: Bool;
	public var bSkipCableUpdateWhenNotOwnerRecentlyRendered: Bool;
	public var bEnableCollision: Bool;
	public var CollisionFriction: cpp.Float32;
	public var CableForce: FVector;
	public var CableGravityScale: cpp.Float32;
	public var CableWidth: cpp.Float32;
	public var NumSides: cpp.Int32;
	public var TileMaterial: cpp.Float32;

	public function SetAttachEndToComponent(Component: cpp.Star<SceneCompComp>, SocketName: FName): Void;
	public function SetAttachEndTo(Actor: cpp.Star<Actor>, ComponentProperty: FName, SocketName: FName): Void;
	public function GetCableParticleLocations(Locations: cpp.Reference<TArray<FVector>>): Void;
	public function GetAttachedComponent(): cpp.Reference<cpp.Star<SceneCompComp>>;
	public function GetAttachedActor(): cpp.Reference<cpp.Star<Actor>>;
}

@:forward(GetCableParticleLocations, GetAttachedComponent, GetAttachedActor)
abstract ConstCableCompComp(CableCompComp) from CableCompComp {
}