// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UCameraAnimationSequence")
@:include("CameraAnimationSequence.h")
extern class CameraAnimationSequence extends TemplateSequence {
}

@:forward()
@:nativeGen
abstract ConstCameraAnimationSequence(CameraAnimationSequence) from CameraAnimationSequence {
}