// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FConstraintInstanceAccessor")
@:include("PhysicsEngine/ConstraintInstance.h")
extern class ConstraintInstanceAccessor {
	public var Owner: TWeakObjectPtr<Object>;
	public var Index: cpp.UInt32;
}