// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UControlRigShapeLibraryFactory")
@:include("ControlRigGizmoLibraryFactory.h")
extern class ControlRigShapeLibraryFactory extends Factory {
}

@:forward()
@:nativeGen
abstract ConstControlRigShapeLibraryFactory(ControlRigShapeLibraryFactory) from ControlRigShapeLibraryFactory {
}