// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDialogueVoiceFactory")
@:include("Factories/DialogueVoiceFactory.h")
@:structAccess
extern class DialogueVoiceFactory extends Factory {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstDialogueVoiceFactory(DialogueVoiceFactory) from DialogueVoiceFactory {
}