// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDrawPolyPathTool")
@:include("DrawPolyPathTool.h")
@:structAccess
extern class DrawPolyPathTool extends InteractiveTool {
	public var OutputTypeProperties: cpp.Star<CreateMeshObjectTypeProperties>;
	public var TransformProps: cpp.Star<DrawPolyPathProperties>;
	public var ExtrudeProperties: cpp.Star<DrawPolyPathExtrudeProperties>;
	public var MaterialProperties: cpp.Star<NewMeshMaterialProperties>;
	public var PlaneMechanic: cpp.Star<ConstructionPlaneMechanic>;
	public var EditPreview: cpp.Star<PolyEditPreviewMesh>;
	public var ExtrudeHeightMechanic: cpp.Star<PlaneDistanceFromHitMechanic>;
	public var CurveDistMechanic: cpp.Star<SpatialCurveDistanceMechanic>;
	public var SurfacePathMechanic: cpp.Star<CollectSurfacePathMechanic>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstDrawPolyPathTool(DrawPolyPathTool) from DrawPolyPathTool {
	public extern var OutputTypeProperties(get, never): cpp.Star<CreateMeshObjectTypeProperties.ConstCreateMeshObjectTypeProperties>;
	public inline extern function get_OutputTypeProperties(): cpp.Star<CreateMeshObjectTypeProperties.ConstCreateMeshObjectTypeProperties> return this.OutputTypeProperties;
	public extern var TransformProps(get, never): cpp.Star<DrawPolyPathProperties.ConstDrawPolyPathProperties>;
	public inline extern function get_TransformProps(): cpp.Star<DrawPolyPathProperties.ConstDrawPolyPathProperties> return this.TransformProps;
	public extern var ExtrudeProperties(get, never): cpp.Star<DrawPolyPathExtrudeProperties.ConstDrawPolyPathExtrudeProperties>;
	public inline extern function get_ExtrudeProperties(): cpp.Star<DrawPolyPathExtrudeProperties.ConstDrawPolyPathExtrudeProperties> return this.ExtrudeProperties;
	public extern var MaterialProperties(get, never): cpp.Star<NewMeshMaterialProperties.ConstNewMeshMaterialProperties>;
	public inline extern function get_MaterialProperties(): cpp.Star<NewMeshMaterialProperties.ConstNewMeshMaterialProperties> return this.MaterialProperties;
	public extern var PlaneMechanic(get, never): cpp.Star<ConstructionPlaneMechanic.ConstConstructionPlaneMechanic>;
	public inline extern function get_PlaneMechanic(): cpp.Star<ConstructionPlaneMechanic.ConstConstructionPlaneMechanic> return this.PlaneMechanic;
	public extern var EditPreview(get, never): cpp.Star<PolyEditPreviewMesh.ConstPolyEditPreviewMesh>;
	public inline extern function get_EditPreview(): cpp.Star<PolyEditPreviewMesh.ConstPolyEditPreviewMesh> return this.EditPreview;
	public extern var ExtrudeHeightMechanic(get, never): cpp.Star<PlaneDistanceFromHitMechanic.ConstPlaneDistanceFromHitMechanic>;
	public inline extern function get_ExtrudeHeightMechanic(): cpp.Star<PlaneDistanceFromHitMechanic.ConstPlaneDistanceFromHitMechanic> return this.ExtrudeHeightMechanic;
	public extern var CurveDistMechanic(get, never): cpp.Star<SpatialCurveDistanceMechanic.ConstSpatialCurveDistanceMechanic>;
	public inline extern function get_CurveDistMechanic(): cpp.Star<SpatialCurveDistanceMechanic.ConstSpatialCurveDistanceMechanic> return this.CurveDistMechanic;
	public extern var SurfacePathMechanic(get, never): cpp.Star<CollectSurfacePathMechanic.ConstCollectSurfacePathMechanic>;
	public inline extern function get_SurfacePathMechanic(): cpp.Star<CollectSurfacePathMechanic.ConstCollectSurfacePathMechanic> return this.SurfacePathMechanic;
}

@:forward
@:nativeGen
@:native("DrawPolyPathTool*")
abstract DrawPolyPathToolPtr(cpp.Star<DrawPolyPathTool>) from cpp.Star<DrawPolyPathTool> to cpp.Star<DrawPolyPathTool>{
	@:from
	public static extern inline function fromValue(v: DrawPolyPathTool): DrawPolyPathToolPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DrawPolyPathTool {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}