// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ECompositeTextureMode")
@:include("Engine/TextureDefines.h")
extern class ECompositeTextureMode {
	static var CTM_Disabled: ECompositeTextureMode;
	static var CTM_NormalRoughnessToRed: ECompositeTextureMode;
	static var CTM_NormalRoughnessToGreen: ECompositeTextureMode;
	static var CTM_NormalRoughnessToBlue: ECompositeTextureMode;
	static var CTM_NormalRoughnessToAlpha: ECompositeTextureMode;
	static var CTM_MAX: ECompositeTextureMode;
}