// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EDatasmithImportLightmapMin")
@:include("DatasmithImportOptions.h")
extern enum EDatasmithImportLightmapMin {
	LIGHTMAP_16;
	LIGHTMAP_32;
	LIGHTMAP_64;
	LIGHTMAP_128;
	LIGHTMAP_256;
	LIGHTMAP_512;
	LIGHTMAP_MAX;
}