// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EDisplaceMeshToolChannelType")
@:include("DisplaceMeshTool.h")
extern enum EDisplaceMeshToolChannelType {
	Red;
	Green;
	Blue;
	Alpha;
	EDisplaceMeshToolChannelType_MAX;
}