// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorUtilityBlueprintAsyncActionBase")
@:include("EditorUtilityLibrary.h")
@:structAccess
extern class EditorUtilityBlueprintAsyncActionBase extends BlueprintAsyncActionBase {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstEditorUtilityBlueprintAsyncActionBase(EditorUtilityBlueprintAsyncActionBase) from EditorUtilityBlueprintAsyncActionBase {
}