// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EGroomOverrideType")
@:include("GroomAssetInterpolation.h")
extern enum EGroomOverrideType {
	Auto;
	Enable;
	Disable;
	EGroomOverrideType_MAX;
}