// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EGroomGeometryType")
@:include("GroomAssetInterpolation.h")
extern enum EGroomGeometryType {
	Strands;
	Cards;
	Meshes;
	EGroomGeometryType_MAX;
}