// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ELandscapeToolErosionMode")
@:include("LandscapeEditorObject.h")
extern enum ELandscapeToolErosionMode {
	Invalid;
	Both;
	Raise;
	Lower;
	ELandscapeToolErosionMode_MAX;
}