// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ELerpInterpolationMode.Type")
@:include("Kismet/KismetMathLibrary.h")
extern enum ELerpInterpolationMode {
	QuatInterp;
	EulerInterp;
	DualQuatInterp;
	ELerpInterpolationMode_MAX;
}