// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ELoadLevelAtStartup.Type")
@:include("Settings/EditorLoadingSavingSettings.h")
extern enum ELoadLevelAtStartup {
	None;
	ProjectDefault;
	LastOpened;
	ELoadLevelAtStartup_MAX;
}