// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EMeshBoundaryConstraint")
@:include("Properties/RemeshProperties.h")
extern enum EMeshBoundaryConstraint {
	Fixed;
	Refine;
	Free;
	EMeshBoundaryConstraint_MAX;
}