// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ENiagaraModuleDependencyType")
@:include("NiagaraScript.h")
extern class ENiagaraModuleDependencyType {
	static var PreDependency: ENiagaraModuleDependencyType;
	static var PostDependency: ENiagaraModuleDependencyType;
	static var ENiagaraModuleDependencyType_MAX: ENiagaraModuleDependencyType;
}