// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ENiagaraGpuDispatchType")
@:include("NiagaraScriptBase.h")
extern enum ENiagaraGpuDispatchType {
	OneD;
	TwoD;
	ThreeD;
	Custom;
	ENiagaraGpuDispatchType_MAX;
}