// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EObjectStateTypeEnum")
@:include("GeometryCollection/GeometryCollectionSimulationTypes.h")
extern class EObjectStateTypeEnum {
	static var Chaos_NONE: EObjectStateTypeEnum;
	static var Chaos_Object_Sleeping: EObjectStateTypeEnum;
	static var Chaos_Object_Kinematic: EObjectStateTypeEnum;
	static var Chaos_Object_Static: EObjectStateTypeEnum;
	static var Chaos_Object_Dynamic: EObjectStateTypeEnum;
	static var Chaos_Object_UserDefined: EObjectStateTypeEnum;
	static var Chaos_Max: EObjectStateTypeEnum;
	static var Chaos_MAX: EObjectStateTypeEnum;
}