// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EPathExistanceQueryType.Type")
@:include("BehaviorTree/Decorators/BTDecorator_DoesPathExist.h")
extern class EPathExistanceQueryType {
	static var NavmeshRaycast2D: EPathExistanceQueryType;
	static var HierarchicalQuery: EPathExistanceQueryType;
	static var RegularPathFinding: EPathExistanceQueryType;
	static var EPathExistanceQueryType_MAX: EPathExistanceQueryType;
}