// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EProceduralSphereType")
@:include("AddPrimitiveTool.h")
extern enum EProceduralSphereType {
	LatLong;
	Box;
	EProceduralSphereType_MAX;
}