// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EPropertyEditorTestUnderscores")
@:include("Editor/PropertyEditorTestObject.h")
extern enum EPropertyEditorTestUnderscores {
	_One;
	_Two;
	_Three;
	NotUnderscore;
	EPropertyEditorTestUnderscores_MAX;
}