// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ERingModulatorTypeSourceEffect")
@:include("SourceEffects/SourceEffectRingModulation.h")
extern class ERingModulatorTypeSourceEffect {
	static var Sine: ERingModulatorTypeSourceEffect;
	static var Saw: ERingModulatorTypeSourceEffect;
	static var Triangle: ERingModulatorTypeSourceEffect;
	static var Square: ERingModulatorTypeSourceEffect;
	static var Count: ERingModulatorTypeSourceEffect;
	static var ERingModulatorTypeSourceEffect_MAX: ERingModulatorTypeSourceEffect;
}