// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ETransitionLogicType.Type")
@:include("Animation/AnimStateMachineTypes.h")
extern enum ETransitionLogicType {
	TLT_StandardBlend;
	TLT_Inertialization;
	TLT_Custom;
	TLT_MAX;
}