// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EVolumeSelectionMethod")
@:include("Private/FractureToolSelection.h")
extern class EVolumeSelectionMethod {
	static var CubeRootOfVolume: EVolumeSelectionMethod;
	static var RelativeToWhole: EVolumeSelectionMethod;
	static var RelativeToLargest: EVolumeSelectionMethod;
	static var EVolumeSelectionMethod_MAX: EVolumeSelectionMethod;
}