// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EWorldPositionIncludedOffsets")
@:include("Materials/MaterialExpressionWorldPosition.h")
extern class EWorldPositionIncludedOffsets {
	static var WPT_Default: EWorldPositionIncludedOffsets;
	static var WPT_ExcludeAllShaderOffsets: EWorldPositionIncludedOffsets;
	static var WPT_CameraRelative: EWorldPositionIncludedOffsets;
	static var WPT_CameraRelativeNoOffsets: EWorldPositionIncludedOffsets;
	static var WPT_MAX: EWorldPositionIncludedOffsets;
}