// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FFavoritedBlueprintPaletteItem")
@:include("BlueprintPaletteFavorites.h")
extern class FavoritedBlueprintPaletteItem {
}