// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FCollisionResponseContainer")
@:include("Engine/EngineTypes.h")
extern class FCollisionResponseContainer {
	public var WorldStatic: ECollisionResponse;
	public var WorldDynamic: ECollisionResponse;
	public var Pawn: ECollisionResponse;
	public var Visibility: ECollisionResponse;
	public var Camera: ECollisionResponse;
	public var PhysicsBody: ECollisionResponse;
	public var Vehicle: ECollisionResponse;
	public var Destructible: ECollisionResponse;
	public var EngineTraceChannel1: ECollisionResponse;
	public var EngineTraceChannel2: ECollisionResponse;
	public var EngineTraceChannel3: ECollisionResponse;
	public var EngineTraceChannel4: ECollisionResponse;
	public var EngineTraceChannel5: ECollisionResponse;
	public var EngineTraceChannel6: ECollisionResponse;
	public var GameTraceChannel1: ECollisionResponse;
	public var GameTraceChannel2: ECollisionResponse;
	public var GameTraceChannel3: ECollisionResponse;
	public var GameTraceChannel4: ECollisionResponse;
	public var GameTraceChannel5: ECollisionResponse;
	public var GameTraceChannel6: ECollisionResponse;
	public var GameTraceChannel7: ECollisionResponse;
	public var GameTraceChannel8: ECollisionResponse;
	public var GameTraceChannel9: ECollisionResponse;
	public var GameTraceChannel10: ECollisionResponse;
	public var GameTraceChannel11: ECollisionResponse;
	public var GameTraceChannel12: ECollisionResponse;
	public var GameTraceChannel13: ECollisionResponse;
	public var GameTraceChannel14: ECollisionResponse;
	public var GameTraceChannel15: ECollisionResponse;
	public var GameTraceChannel16: ECollisionResponse;
	public var GameTraceChannel17: ECollisionResponse;
	public var GameTraceChannel18: ECollisionResponse;
}