// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FDropNoteInfo")
@:include("Engine/Engine.h")
extern class FDropNoteInfo {
	public var Location: FVector;
	public var Rotation: FRotator;
	public var Comment: FString;
}