// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FFieldObjectCommands")
@:include("Field/FieldSystemObjects.h")
extern class FFieldObjectCommands {
	public var TargetNames: TArray<FName>;
	public var RootNodes: TArray<TObjectPtr<UFieldNodeBase>>;
	public var MetaDatas: TArray<TObjectPtr<UFieldSystemMetaData>>;
}