// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FHairExternalForces")
@:include("GroomAssetPhysics.h")
extern class FHairExternalForces {
	public var GravityVector: FVector;
	public var AirDrag: cpp.Float32;
	public var AirVelocity: FVector;
}