// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FHLODInstancingKey")
@:include("Engine/LODActor.h")
extern class FHLODInstancingKey {
	public var StaticMesh: TObjectPtr<UStaticMesh>;
	public var Material: TObjectPtr<UMaterialInterface>;
}