// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FInt32Interval")
@:include("UObject/NoExportTypes.h")
extern class FInt32Interval {
	public var Min: cpp.Int32;
	public var Max: cpp.Int32;
}