// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FKBoxElem")
@:include("PhysicsEngine/BoxElem.h")
extern class FKBoxElem extends FKShapeElem {
	public var TM_DEPRECATED: FMatrix;
	public var Orientation_DEPRECATED: FQuat;
	public var Center: FVector;
	public var Rotation: FRotator;
	public var X: cpp.Float32;
	public var Y: cpp.Float32;
	public var Z: cpp.Float32;
}