// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FKShapeElem")
@:include("PhysicsEngine/ShapeElem.h")
extern class FKShapeElem {
	public var RestOffset: cpp.Float32;
	public var bIsGenerated: Bool;
	public var Name: FName;
	public var bContributeToMass: Bool;
	public var CollisionEnabled: ECollisionEnabled;
}