// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FFloatRangeBound")
@:include("UObject/NoExportTypes.h")
@:structAccess
extern class FloatRangeBound {
	public var Type: ERangeBoundTypes;
	public var Value: cpp.Float32;

	@:native("FFloatRangeBound") public function new();
	@:native("FFloatRangeBound") public static function make(Type: ERangeBoundTypes, Value: cpp.Float32): FloatRangeBound ;
}