// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UFloatChannelKeyProxy")
@:include("Channels/FloatChannelKeyProxy.h")
extern class FloatChannelKeyProxy extends Object {
	public var Time: FrameNumber;
	public var Value: MovieSceneFloatValue;
}

@:forward()
@:nativeGen
abstract ConstFloatChannelKeyProxy(FloatChannelKeyProxy) from FloatChannelKeyProxy {
	public extern var Time(get, never): FrameNumber;
	public inline extern function get_Time(): FrameNumber return this.Time;
	public extern var Value(get, never): MovieSceneFloatValue;
	public inline extern function get_Value(): MovieSceneFloatValue return this.Value;
}