// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FNiagaraDataSetID")
@:include("NiagaraCommon.h")
extern class FNiagaraDataSetID {
	public var Name: FName;
	public var Type: ENiagaraDataSetType;
}