// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FProcMeshTangent")
@:include("ProceduralMeshComponent.h")
extern class FProcMeshTangent {
	public var TangentX: FVector;
	public var bFlipTangentY: Bool;
}