// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FRigVMRuntimeSettings")
@:include("RigVMCore/RigVMExecuteContext.h")
extern class FRigVMRuntimeSettings {
	public var MaximumArraySize: cpp.Int32;
	public var bEnableProfiling: Bool;
}