// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FTwistConstraint")
@:include("PhysicsEngine/ConstraintTypes.h")
extern class FTwistConstraint extends FConstraintBaseParams {
	public var TwistLimitDegrees: cpp.Float32;
	public var TwistMotion: EAngularConstraintMotion;
}