// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGizmoClickTarget")
extern class GizmoClickTarget extends Interface {
	public function UpdateInteractingState(bInteracting: Bool): Void;
	public function UpdateHoverState(bHovering: Bool): Void;
}

@:forward()
@:nativeGen
abstract ConstGizmoClickTarget(GizmoClickTarget) from GizmoClickTarget {
}