// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AHaxeForUnrealCharacter")
@:include("HaxeForUnrealCharacter.h")
@:structAccess
extern class HaxeForUnrealCharacter extends Character {
	public var CameraBoom: cpp.Star<SpringArmComp>;
	public var FollowCamera: cpp.Star<CameraComp>;
	public var TurnRateGamepad: cpp.Float32;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstHaxeForUnrealCharacter(HaxeForUnrealCharacter) from HaxeForUnrealCharacter {
	public extern var CameraBoom(get, never): cpp.Star<SpringArmComp.ConstSpringArmComp>;
	public inline extern function get_CameraBoom(): cpp.Star<SpringArmComp.ConstSpringArmComp> return this.CameraBoom;
	public extern var FollowCamera(get, never): cpp.Star<CameraComp.ConstCameraComp>;
	public inline extern function get_FollowCamera(): cpp.Star<CameraComp.ConstCameraComp> return this.FollowCamera;
	public extern var TurnRateGamepad(get, never): cpp.Float32;
	public inline extern function get_TurnRateGamepad(): cpp.Float32 return this.TurnRateGamepad;
}

@:forward
@:nativeGen
@:native("HaxeForUnrealCharacter*")
abstract HaxeForUnrealCharacterPtr(cpp.Star<HaxeForUnrealCharacter>) from cpp.Star<HaxeForUnrealCharacter> to cpp.Star<HaxeForUnrealCharacter>{
	@:from
	public static extern inline function fromValue(v: HaxeForUnrealCharacter): HaxeForUnrealCharacterPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): HaxeForUnrealCharacter {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}