// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UHoleFillToolProperties")
@:include("HoleFillTool.h")
extern class HoleFillToolProperties extends InteractiveToolPropertySet {
	public var FillType: EHoleFillOpFillType;
	public var bRemoveIsolatedTriangles: Bool;
	public var bQuickFillSmallHoles: Bool;
}

@:forward()
@:nativeGen
abstract ConstHoleFillToolProperties(HoleFillToolProperties) from HoleFillToolProperties {
	public extern var FillType(get, never): EHoleFillOpFillType;
	public inline extern function get_FillType(): EHoleFillOpFillType return this.FillType;
	public extern var bRemoveIsolatedTriangles(get, never): Bool;
	public inline extern function get_bRemoveIsolatedTriangles(): Bool return this.bRemoveIsolatedTriangles;
	public extern var bQuickFillSmallHoles(get, never): Bool;
	public inline extern function get_bQuickFillSmallHoles(): Bool return this.bQuickFillSmallHoles;
}