// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UInterpTrackAnimControl")
@:include("Matinee/InterpTrackAnimControl.h")
@:structAccess
extern class InterpTrackAnimControl extends InterpTrackFloatBase {
	public var SlotName: FName;
	public var AnimSeqs: TArray<AnimControlTrackKey>;
	public var bSkipAnimNotifiers: Bool;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstInterpTrackAnimControl(InterpTrackAnimControl) from InterpTrackAnimControl {
	public extern var SlotName(get, never): FName;
	public inline extern function get_SlotName(): FName return this.SlotName;
	public extern var AnimSeqs(get, never): TArray<AnimControlTrackKey>;
	public inline extern function get_AnimSeqs(): TArray<AnimControlTrackKey> return this.AnimSeqs;
	public extern var bSkipAnimNotifiers(get, never): Bool;
	public inline extern function get_bSkipAnimNotifiers(): Bool return this.bSkipAnimNotifiers;
}