// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UK2Node_ConvertToPNG")
@:include("AppleImageUtilsBlueprintSupport.h")
@:structAccess
extern class K2Node_ConvertToPNG extends K2Node_BaseAsyncTask {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstK2Node_ConvertToPNG(K2Node_ConvertToPNG) from K2Node_ConvertToPNG {
}

@:forward
@:nativeGen
@:native("K2Node_ConvertToPNG*")
abstract K2Node_ConvertToPNGPtr(cpp.Star<K2Node_ConvertToPNG>) from cpp.Star<K2Node_ConvertToPNG> to cpp.Star<K2Node_ConvertToPNG>{
	@:from
	public static extern inline function fromValue(v: K2Node_ConvertToPNG): K2Node_ConvertToPNGPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): K2Node_ConvertToPNG {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}