// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ULinkerPlaceholderExportObject")
extern class LinkerPlaceholderExportObject extends Object {
}

@:forward()
@:nativeGen
abstract ConstLinkerPlaceholderExportObject(LinkerPlaceholderExportObject) from LinkerPlaceholderExportObject {
}