// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ULiveLinkFrameInterpolationProcessor")
@:include("LiveLinkFrameInterpolationProcessor.h")
extern class LiveLinkFrameInterpolationProcessor extends Object {
}

@:forward()
@:nativeGen
abstract ConstLiveLinkFrameInterpolationProcessor(LiveLinkFrameInterpolationProcessor) from LiveLinkFrameInterpolationProcessor {
}