// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionCameraVectorWS")
@:include("Materials/MaterialExpressionCameraVectorWS.h")
extern class MaterialExpressionCameraVectorWS extends MaterialExpression {
}

@:forward()
@:nativeGen
abstract ConstMaterialExpressionCameraVectorWS(MaterialExpressionCameraVectorWS) from MaterialExpressionCameraVectorWS {
}