// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMeshSculptToolBase")
@:include("Sculpting/MeshSculptToolBase.h")
@:structAccess
extern class MeshSculptToolBase extends MeshSurfacePointTool {
	public var BrushProperties: cpp.Star<SculptBrushProperties>;
	public var GizmoProperties: cpp.Star<WorkPlaneProperties>;
	public var BrushOpPropSets: TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps>>;
	public var SecondaryBrushOpPropSets: TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps>>;
	public var ViewProperties: cpp.Star<MeshEditingViewProperties>;
	public var ActiveOverrideMaterial: cpp.Star<MaterialInstanceDynamic>;
	public var BrushIndicator: cpp.Star<BrushStampIndicator>;
	public var bIsVolumetricIndicator: Bool;
	public var BrushIndicatorMaterial: cpp.Star<MaterialInstanceDynamic>;
	public var BrushIndicatorMesh: cpp.Star<PreviewMesh>;
	public var PlaneTransformGizmo: cpp.Star<CombinedTransformGizmo>;
	public var PlaneTransformProxy: cpp.Star<TransformProxy>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMeshSculptToolBase(MeshSculptToolBase) from MeshSculptToolBase {
	public extern var BrushProperties(get, never): cpp.Star<SculptBrushProperties.ConstSculptBrushProperties>;
	public inline extern function get_BrushProperties(): cpp.Star<SculptBrushProperties.ConstSculptBrushProperties> return this.BrushProperties;
	public extern var GizmoProperties(get, never): cpp.Star<WorkPlaneProperties.ConstWorkPlaneProperties>;
	public inline extern function get_GizmoProperties(): cpp.Star<WorkPlaneProperties.ConstWorkPlaneProperties> return this.GizmoProperties;
	public extern var BrushOpPropSets(get, never): TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps.ConstMeshSculptBrushOpProps>>;
	public inline extern function get_BrushOpPropSets(): TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps.ConstMeshSculptBrushOpProps>> return this.BrushOpPropSets;
	public extern var SecondaryBrushOpPropSets(get, never): TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps.ConstMeshSculptBrushOpProps>>;
	public inline extern function get_SecondaryBrushOpPropSets(): TMap<cpp.Int32, cpp.Star<MeshSculptBrushOpProps.ConstMeshSculptBrushOpProps>> return this.SecondaryBrushOpPropSets;
	public extern var ViewProperties(get, never): cpp.Star<MeshEditingViewProperties.ConstMeshEditingViewProperties>;
	public inline extern function get_ViewProperties(): cpp.Star<MeshEditingViewProperties.ConstMeshEditingViewProperties> return this.ViewProperties;
	public extern var ActiveOverrideMaterial(get, never): cpp.Star<MaterialInstanceDynamic.ConstMaterialInstanceDynamic>;
	public inline extern function get_ActiveOverrideMaterial(): cpp.Star<MaterialInstanceDynamic.ConstMaterialInstanceDynamic> return this.ActiveOverrideMaterial;
	public extern var BrushIndicator(get, never): cpp.Star<BrushStampIndicator.ConstBrushStampIndicator>;
	public inline extern function get_BrushIndicator(): cpp.Star<BrushStampIndicator.ConstBrushStampIndicator> return this.BrushIndicator;
	public extern var bIsVolumetricIndicator(get, never): Bool;
	public inline extern function get_bIsVolumetricIndicator(): Bool return this.bIsVolumetricIndicator;
	public extern var BrushIndicatorMaterial(get, never): cpp.Star<MaterialInstanceDynamic.ConstMaterialInstanceDynamic>;
	public inline extern function get_BrushIndicatorMaterial(): cpp.Star<MaterialInstanceDynamic.ConstMaterialInstanceDynamic> return this.BrushIndicatorMaterial;
	public extern var BrushIndicatorMesh(get, never): cpp.Star<PreviewMesh.ConstPreviewMesh>;
	public inline extern function get_BrushIndicatorMesh(): cpp.Star<PreviewMesh.ConstPreviewMesh> return this.BrushIndicatorMesh;
	public extern var PlaneTransformGizmo(get, never): cpp.Star<CombinedTransformGizmo.ConstCombinedTransformGizmo>;
	public inline extern function get_PlaneTransformGizmo(): cpp.Star<CombinedTransformGizmo.ConstCombinedTransformGizmo> return this.PlaneTransformGizmo;
	public extern var PlaneTransformProxy(get, never): cpp.Star<TransformProxy.ConstTransformProxy>;
	public inline extern function get_PlaneTransformProxy(): cpp.Star<TransformProxy.ConstTransformProxy> return this.PlaneTransformProxy;
}

@:forward
@:nativeGen
@:native("MeshSculptToolBase*")
abstract MeshSculptToolBasePtr(cpp.Star<MeshSculptToolBase>) from cpp.Star<MeshSculptToolBase> to cpp.Star<MeshSculptToolBase>{
	@:from
	public static extern inline function fromValue(v: MeshSculptToolBase): MeshSculptToolBasePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MeshSculptToolBase {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}