// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FModelingModeAssetCollectionSet")
@:include("ModelingToolsEditorModeSettings.h")
extern class ModelingModeAssetCollectionSet {
	public var Name: FString;
	public var Collections: TArray<CollectionReference>;
}