// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneDoubleSection")
@:include("Sections/MovieSceneDoubleSection.h")
@:structAccess
extern class MovieSceneDoubleSection extends MovieSceneSection {
	@:protected public var DoubleCurve: MovieSceneDoubleChannel;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieSceneDoubleSection(MovieSceneDoubleSection) from MovieSceneDoubleSection {
}

@:forward
@:nativeGen
@:native("MovieSceneDoubleSection*")
abstract MovieSceneDoubleSectionPtr(cpp.Star<MovieSceneDoubleSection>) from cpp.Star<MovieSceneDoubleSection> to cpp.Star<MovieSceneDoubleSection>{
	@:from
	public static extern inline function fromValue(v: MovieSceneDoubleSection): MovieSceneDoubleSectionPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MovieSceneDoubleSection {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}