// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneSequenceTickManager")
@:include("MovieSceneSequenceTickManager.h")
@:structAccess
extern class MovieSceneSequenceTickManager extends Object {
	public var SequenceActors: TArray<MovieSceneSequenceActorPointers>;
	public var Linker: cpp.Star<MovieSceneEntitySystemLinker>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieSceneSequenceTickManager(MovieSceneSequenceTickManager) from MovieSceneSequenceTickManager {
	public extern var SequenceActors(get, never): TArray<MovieSceneSequenceActorPointers>;
	public inline extern function get_SequenceActors(): TArray<MovieSceneSequenceActorPointers> return this.SequenceActors;
	public extern var Linker(get, never): cpp.Star<MovieSceneEntitySystemLinker.ConstMovieSceneEntitySystemLinker>;
	public inline extern function get_Linker(): cpp.Star<MovieSceneEntitySystemLinker.ConstMovieSceneEntitySystemLinker> return this.Linker;
}

@:forward
@:nativeGen
@:native("MovieSceneSequenceTickManager*")
abstract MovieSceneSequenceTickManagerPtr(cpp.Star<MovieSceneSequenceTickManager>) from cpp.Star<MovieSceneSequenceTickManager> to cpp.Star<MovieSceneSequenceTickManager>{
	@:from
	public static extern inline function fromValue(v: MovieSceneSequenceTickManager): MovieSceneSequenceTickManagerPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MovieSceneSequenceTickManager {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}