// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneDoubleTrack")
@:include("Tracks/MovieSceneDoubleTrack.h")
extern class MovieSceneDoubleTrack extends MovieScenePropertyTrack {
}

@:forward()
@:nativeGen
abstract ConstMovieSceneDoubleTrack(MovieSceneDoubleTrack) from MovieSceneDoubleTrack {
}