// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNavFilter_AIControllerDefault")
@:include("Navigation/NavFilter_AIControllerDefault.h")
extern class NavFilter_AIControllerDefault extends NavigationQueryFilter {
}

@:forward()
@:nativeGen
abstract ConstNavFilter_AIControllerDefault(NavFilter_AIControllerDefault) from NavFilter_AIControllerDefault {
}