// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraMessageData")
@:include("NiagaraMessages.h")
extern class NiagaraMessageData extends NiagaraMessageDataBase {
}

@:forward()
@:nativeGen
abstract ConstNiagaraMessageData(NiagaraMessageData) from NiagaraMessageData {
}