// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraStackSummaryViewCollapseButton")
@:include("ViewModels/Stack/NiagaraStackEmitterSettingsGroup.h")
extern class NiagaraStackSummaryViewCollapseButton extends NiagaraStackEntry {
}

@:forward()
@:nativeGen
abstract ConstNiagaraStackSummaryViewCollapseButton(NiagaraStackSummaryViewCollapseButton) from NiagaraStackSummaryViewCollapseButton {
}