// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UObjectPropertyBase")
@:structAccess
extern class ObjectPropertyBase extends Property {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstObjectPropertyBase(ObjectPropertyBase) from ObjectPropertyBase {
}