// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnAcceptHandleSourcesProperties")
@:include("PropertySets/OnAcceptProperties.h")
extern class OnAcceptHandleSourcesProperties extends OnAcceptHandleSourcesPropertiesBase {
	public var HandleInputs: EHandleSourcesMethod;
}

@:forward()
@:nativeGen
abstract ConstOnAcceptHandleSourcesProperties(OnAcceptHandleSourcesProperties) from OnAcceptHandleSourcesProperties {
	public extern var HandleInputs(get, never): EHandleSourcesMethod;
	public inline extern function get_HandleInputs(): EHandleSourcesMethod return this.HandleInputs;
}