// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnAnimInitialized__PythonCallable")
extern class OnAnimInitialized__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstOnAnimInitialized__PythonCallable(OnAnimInitialized__PythonCallable) from OnAnimInitialized__PythonCallable {
}