// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnMenuOpenChangedEvent__PythonCallable")
extern class OnMenuOpenChangedEvent__PythonCallable extends PythonCallableForDelegate {
}

@:forward()
@:nativeGen
abstract ConstOnMenuOpenChangedEvent__PythonCallable(OnMenuOpenChangedEvent__PythonCallable) from OnMenuOpenChangedEvent__PythonCallable {
}