// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPaperTileMapFactory")
@:include("PaperTileMapFactory.h")
@:structAccess
extern class PaperTileMapFactory extends Factory {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstPaperTileMapFactory(PaperTileMapFactory) from PaperTileMapFactory {
}

@:forward
@:nativeGen
@:native("PaperTileMapFactory*")
abstract PaperTileMapFactoryPtr(cpp.Star<PaperTileMapFactory>) from cpp.Star<PaperTileMapFactory> to cpp.Star<PaperTileMapFactory>{
	@:from
	public static extern inline function fromValue(v: PaperTileMapFactory): PaperTileMapFactoryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): PaperTileMapFactory {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}