// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FPawnActionStack")
@:include("Actions/PawnActionsComponent.h")
@:structAccess
extern class PawnActionStack {
	private var TopAction: cpp.Star<PawnAction>;

	@:native("FPawnActionStack") public function new();
	@:native("FPawnActionStack") public static function make(TopAction: cpp.Star<PawnAction>): PawnActionStack ;
}