// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPolygonOnMeshTool")
@:include("PolygonOnMeshTool.h")
@:structAccess
extern class PolygonOnMeshTool extends SingleSelectionMeshEditingTool {
	@:protected public var BasicProperties: cpp.Star<PolygonOnMeshToolProperties>;
	@:protected public var ActionProperties: cpp.Star<PolygonOnMeshToolActionPropertySet>;
	@:protected public var Preview: cpp.Star<MeshOpPreviewWithBackgroundCompute>;
	@:protected public var DrawnLineSet: cpp.Star<LineSetComp>;
	@:protected public var PlaneMechanic: cpp.Star<ConstructionPlaneMechanic>;
	@:protected public var DrawPolygonMechanic: cpp.Star<CollectSurfacePathMechanic>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstPolygonOnMeshTool(PolygonOnMeshTool) from PolygonOnMeshTool {
}

@:forward
@:nativeGen
@:native("PolygonOnMeshTool*")
abstract PolygonOnMeshToolPtr(cpp.Star<PolygonOnMeshTool>) from cpp.Star<PolygonOnMeshTool> to cpp.Star<PolygonOnMeshTool>{
	@:from
	public static extern inline function fromValue(v: PolygonOnMeshTool): PolygonOnMeshToolPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): PolygonOnMeshTool {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}