// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPopulateDialogueWaveFromCharacterSheetCommandlet")
@:include("Commandlets/PopulateDialogueWaveFromCharacterSheetCommandlet.h")
extern class PopulateDialogueWaveFromCharacterSheetCommandlet extends Commandlet {
}

@:forward()
@:nativeGen
abstract ConstPopulateDialogueWaveFromCharacterSheetCommandlet(PopulateDialogueWaveFromCharacterSheetCommandlet) from PopulateDialogueWaveFromCharacterSheetCommandlet {
}