// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FRigVMByteCodeStatistics")
@:include("RigVMCore/RigVMStatistics.h")
@:structAccess
extern class RigVMByteCodeStatistics {
	public var InstructionCount: cpp.Int32;
	public var DataBytes: cpp.Int32;

	@:native("FRigVMByteCodeStatistics") public function new();
	@:native("FRigVMByteCodeStatistics") public static function make(InstructionCount: cpp.Int32, DataBytes: cpp.Int32): RigVMByteCodeStatistics ;
}