// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URuntimeVirtualTextureThumbnailRenderer")
@:include("RuntimeVirtualTextureThumbnailRenderer.h")
@:structAccess
extern class RuntimeVirtualTextureThumbnailRenderer extends DefaultSizedThumbnailRenderer {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstRuntimeVirtualTextureThumbnailRenderer(RuntimeVirtualTextureThumbnailRenderer) from RuntimeVirtualTextureThumbnailRenderer {
}