// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ARuntimeVirtualTextureVolume")
@:include("VT/RuntimeVirtualTextureVolume.h")
@:structAccess
extern class RuntimeVirtualTextureVolume extends Actor {
	public var VirtualTextureComponent: cpp.Star<RuntimeVirtualTextureComp>;
	public var Box: cpp.Star<BoxComp>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstRuntimeVirtualTextureVolume(RuntimeVirtualTextureVolume) from RuntimeVirtualTextureVolume {
	public extern var VirtualTextureComponent(get, never): cpp.Star<RuntimeVirtualTextureComp.ConstRuntimeVirtualTextureComp>;
	public inline extern function get_VirtualTextureComponent(): cpp.Star<RuntimeVirtualTextureComp.ConstRuntimeVirtualTextureComp> return this.VirtualTextureComponent;
	public extern var Box(get, never): cpp.Star<BoxComp.ConstBoxComp>;
	public inline extern function get_Box(): cpp.Star<BoxComp.ConstBoxComp> return this.Box;
}

@:forward
@:nativeGen
@:native("RuntimeVirtualTextureVolume*")
abstract RuntimeVirtualTextureVolumePtr(cpp.Star<RuntimeVirtualTextureVolume>) from cpp.Star<RuntimeVirtualTextureVolume> to cpp.Star<RuntimeVirtualTextureVolume>{
	@:from
	public static extern inline function fromValue(v: RuntimeVirtualTextureVolume): RuntimeVirtualTextureVolumePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): RuntimeVirtualTextureVolume {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}