// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USkeletalControlLibrary")
@:include("SkeletalControlLibrary.h")
@:structAccess
extern class SkeletalControlLibrary extends BlueprintFunctionLibrary {
	public function SetAlpha(SkeletalControl: cpp.Reference<SkeletalControlReference>, Alpha: cpp.Float32): SkeletalControlReference;
	public function GetAlpha(SkeletalControl: cpp.Reference<SkeletalControlReference>): cpp.Float32;
	public function ConvertToSkeletalControlPure(Node: cpp.Reference<AnimNodeReference>, SkeletalControl: cpp.Reference<SkeletalControlReference>, Result: cpp.Reference<Bool>): Void;
	public function ConvertToSkeletalControl(Node: cpp.Reference<AnimNodeReference>, Result: cpp.Reference<EAnimNodeReferenceConversionResult>): SkeletalControlReference;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstSkeletalControlLibrary(SkeletalControlLibrary) from SkeletalControlLibrary {
}

@:forward
@:nativeGen
@:native("SkeletalControlLibrary*")
abstract SkeletalControlLibraryPtr(cpp.Star<SkeletalControlLibrary>) from cpp.Star<SkeletalControlLibrary> to cpp.Star<SkeletalControlLibrary>{
	@:from
	public static extern inline function fromValue(v: SkeletalControlLibrary): SkeletalControlLibraryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): SkeletalControlLibrary {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}