// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USkeletalMeshReadOnlyToolTarget")
@:include("ToolTargets/SkeletalMeshToolTarget.h")
extern class SkeletalMeshReadOnlyToolTarget extends ToolTarget {
}

@:forward()
@:nativeGen
abstract ConstSkeletalMeshReadOnlyToolTarget(SkeletalMeshReadOnlyToolTarget) from SkeletalMeshReadOnlyToolTarget {
}