// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USmoothBrushOpProps")
@:include("Sculpting/MeshSmoothingBrushOps.h")
@:structAccess
extern class SmoothBrushOpProps extends BaseSmoothBrushOpProps {
	public var Strength: cpp.Float32;
	public var Falloff: cpp.Float32;
	public var bPreserveUVFlow: Bool;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstSmoothBrushOpProps(SmoothBrushOpProps) from SmoothBrushOpProps {
	public extern var Strength(get, never): cpp.Float32;
	public inline extern function get_Strength(): cpp.Float32 return this.Strength;
	public extern var Falloff(get, never): cpp.Float32;
	public inline extern function get_Falloff(): cpp.Float32 return this.Falloff;
	public extern var bPreserveUVFlow(get, never): Bool;
	public inline extern function get_bPreserveUVFlow(): Bool return this.bPreserveUVFlow;
}

@:forward
@:nativeGen
@:native("SmoothBrushOpProps*")
abstract SmoothBrushOpPropsPtr(cpp.Star<SmoothBrushOpProps>) from cpp.Star<SmoothBrushOpProps> to cpp.Star<SmoothBrushOpProps>{
	@:from
	public static extern inline function fromValue(v: SmoothBrushOpProps): SmoothBrushOpPropsPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): SmoothBrushOpProps {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}