// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimGraphNode_StateMachineBase")
@:include("AnimGraphNode_StateMachineBase.h")
extern class UAnimGraphNode_StateMachineBase extends UAnimGraphNode_Base {
	public var EditorStateMachineGraph: TObjectPtr<UAnimationStateMachineGraph>;
}
