// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimationSharingSetupFactory")
@:include("AnimationSharingSetupFactory.h")
extern class UAnimationSharingSetupFactory extends UFactory {
}
