// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimCompress_RemoveEverySecondKey")
@:include("Animation/AnimCompress_RemoveEverySecondKey.h")
extern class UAnimCompress_RemoveEverySecondKey extends UAnimCompress {
	public var MinKeys: cpp.Int32;
	public var bStartAtSecondKey: Bool;
}
