// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UARTypesDummyClass")
@:include("ARTypes.h")
extern class UARTypesDummyClass extends UObject {
}
