// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBakeCurvatureMapToolProperties")
@:include("BakeMeshAttributeToolCommon.h")
extern class UBakeCurvatureMapToolProperties extends UInteractiveToolPropertySet {
	public var CurvatureType: EBakeCurvatureTypeMode;
	public var ColorMapping: EBakeCurvatureColorMode;
	public var ColorRangeMultiplier: cpp.Float32;
	public var MinRangeMultiplier: cpp.Float32;
	public var Clamping: EBakeCurvatureClampMode;
}
