// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBehaviorTreeGraphNode_Composite")
@:include("BehaviorTreeGraphNode_Composite.h")
extern class UBehaviorTreeGraphNode_Composite extends UBehaviorTreeGraphNode {
}
