// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UClothPhysicalMeshDataNv_Legacy")
@:include("ClothPhysicalMeshDataNv_Legacy.h")
extern class UClothPhysicalMeshDataNv_Legacy extends UClothPhysicalMeshDataBase_Legacy {
	public var MaxDistances: TArray<cpp.Float32>;
	public var BackstopDistances: TArray<cpp.Float32>;
	public var BackstopRadiuses: TArray<cpp.Float32>;
	public var AnimDriveMultipliers: TArray<cpp.Float32>;
}
