// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorAnimCompositeSegment")
@:include("Animation/EditorAnimCompositeSegment.h")
extern class UEditorAnimCompositeSegment extends UEditorAnimBaseObj {
	public var AnimSegment: FAnimSegment;
}
