// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEditorLoadingAndSavingUtils")
@:include("FileHelpers.h")
extern class UEditorLoadingAndSavingUtils extends UObject {

	public function UnloadPackages(PackagesToUnload: TArray<cpp.Star<UPackage>>, bOutAnyPackagesUnloaded: Bool, OutErrorMessage: cpp.Reference<FText>): Void;
	public function SavePackagesWithDialog(PackagesToSave: TArray<cpp.Star<UPackage>>, bOnlyDirty: Bool): Bool;
	public function SavePackages(PackagesToSave: TArray<cpp.Star<UPackage>>, bOnlyDirty: Bool): Bool;
	public function SaveMap(World: cpp.Star<UWorld>, AssetPath: FString): Bool;
	public function SaveDirtyPackagesWithDialog(bSaveMapPackages: Bool, bSaveContentPackages: Bool): Bool;
	public function SaveDirtyPackages(bSaveMapPackages: Bool, bSaveContentPackages: Bool): Bool;
	public function SaveCurrentLevel(): Bool;
	public function ReloadPackages(PackagesToReload: TArray<cpp.Star<UPackage>>, bOutAnyPackagesReloaded: Bool, OutErrorMessage: cpp.Reference<FText>, InteractionMode: EReloadPackagesInteractionMode): Void;
	public function NewMapFromTemplate(PathToTemplateLevel: FString, bSaveExistingMap: Bool): cpp.Star<UWorld>;
	public function NewBlankMap(bSaveExistingMap: Bool): cpp.Star<UWorld>;
	public function LoadMapWithDialog(): cpp.Star<UWorld>;
	public function LoadMap(Filename: FString): cpp.Star<UWorld>;
	public function ImportScene(Filename: FString): Void;
	public function GetDirtyMapPackages(OutDirtyPackages: TArray<cpp.Star<UPackage>>): Void;
	public function GetDirtyContentPackages(OutDirtyPackages: TArray<cpp.Star<UPackage>>): Void;
	public function ExportScene(bExportSelectedActorsOnly: Bool): Void;
}
