// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UEnvQueryItemType")
@:include("EnvironmentQuery/Items/EnvQueryItemType.h")
extern class UEnvQueryItemType extends UObject {
}
