// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UForceFeedbackAttenuation")
@:include("GameFramework/ForceFeedbackAttenuation.h")
extern class UForceFeedbackAttenuation extends UObject {
	public var Attenuation: FForceFeedbackAttenuationSettings;
}
