// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UFractureEditorMode")
@:include("FractureEditorMode.h")
extern class UFractureEditorMode extends UBaseLegacyWidgetEdMode {
}
