// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGameplayTask_ClaimResource")
@:include("Tasks/GameplayTask_ClaimResource.h")
extern class UGameplayTask_ClaimResource extends UGameplayTask {

	public function ClaimResources(InTaskOwner: UGameplayTaskOwnerInterface, ResourceClasses: TArray<TSubclassOf<UGameplayTaskResource>>, Priority: cpp.UInt8, TaskInstanceName: FName): cpp.Star<UGameplayTask_ClaimResource>;
	public function ClaimResource(InTaskOwner: UGameplayTaskOwnerInterface, ResourceClass: TSubclassOf<UGameplayTaskResource>, Priority: cpp.UInt8, TaskInstanceName: FName): cpp.Star<UGameplayTask_ClaimResource>;
}
