// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGeometryCollectionCache")
@:include("GeometryCollection/GeometryCollectionCache.h")
extern class UGeometryCollectionCache extends UObject {
	public var RecordedData: FRecordedTransformTrack;
	public var SupportedCollection: TObjectPtr<UGeometryCollection>;
	public var CompatibleCollectionState: FGuid;
}
