// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGizmoTransformProxyTransformSource")
@:include("BaseGizmos/TransformSources.h")
extern class UGizmoTransformProxyTransformSource extends UGizmoBaseTransformSource {
	public var Proxy: TObjectPtr<UTransformProxy>;
}
