// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UImageSequenceProtocol_EXR")
@:include("Protocols/ImageSequenceProtocol.h")
extern class UImageSequenceProtocol_EXR extends UImageSequenceProtocol {
	public var bCompressed: Bool;
	public var CaptureGamut: EHDRCaptureGamut;
}
