// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UInterpTrackInstFloatParticleParam")
@:include("Matinee/InterpTrackInstFloatParticleParam.h")
extern class UInterpTrackInstFloatParticleParam extends UInterpTrackInst {
	public var ResetFloat: cpp.Float32;
}
