// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionReflectionCapturePassSwitch")
@:include("Materials/MaterialExpressionReflectionCapturePassSwitch.h")
extern class UMaterialExpressionReflectionCapturePassSwitch extends UMaterialExpression {
	public var Default: FExpressionInput;
	public var Reflection: FExpressionInput;
}
