// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionChannelMaskParameter")
@:include("Materials/MaterialExpressionChannelMaskParameter.h")
extern class UMaterialExpressionChannelMaskParameter extends UMaterialExpressionVectorParameter {
	public var MaskChannel: EChannelMaskParameterColor;
	public var Input: FExpressionInput;
}
