// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMeshReconstructorBase")
@:include("MeshReconstructorBase.h")
extern class UMeshReconstructorBase extends UObject {

	public function StopReconstruction(): Void;
	public function StartReconstruction(): Void;
	public function PauseReconstruction(): Void;
	public function IsReconstructionStarted(): Bool;
	public function IsReconstructionPaused(): Bool;
	public function DisconnectMRMesh(): Void;
	public function ConnectMRMesh(Mesh: cpp.Star<UMRMeshComponent>): Void;
}
