// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneCameraCutSection")
@:include("Sections/MovieSceneCameraCutSection.h")
extern class UMovieSceneCameraCutSection extends UMovieSceneSection {
	public var bLockPreviousCamera: Bool;
	public var CameraGuid_DEPRECATED: FGuid;
	public var CameraBindingID: FMovieSceneObjectBindingID;
	public var InitialCameraCutTransform: FTransform;
	public var bHasInitialCameraCutTransform: Bool;
	public var ThumbnailReferenceOffset: cpp.Float32;

	public function SetCameraBindingID(InCameraBindingID: FMovieSceneObjectBindingID): Void;
	public function GetCameraBindingID(): FMovieSceneObjectBindingID;
}
