// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneFadeSection")
@:include("Sections/MovieSceneFadeSection.h")
extern class UMovieSceneFadeSection extends UMovieSceneSection {
	public var FloatCurve: FMovieSceneFloatChannel;
	public var FadeColor: FLinearColor;
	public var bFadeAudio: Bool;
}
