// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMulticastInlineDelegatePropertyWrapper")
extern class UMulticastInlineDelegatePropertyWrapper extends UMulticastDelegatePropertyWrapper {
}
