// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraStackSpacer")
@:include("ViewModels/Stack/NiagaraStackEntry.h")
extern class UNiagaraStackSpacer extends UNiagaraStackEntry {
}
