// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraStackItemContent")
@:include("ViewModels/Stack/NiagaraStackItem.h")
extern class UNiagaraStackItemContent extends UNiagaraStackEntry {
}
