// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UOnEditorUtilityPIEEvent__PythonCallable")
extern class UOnEditorUtilityPIEEvent__PythonCallable extends UPythonCallableForDelegate {
}
