// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPackageTools")
@:include("PackageTools.h")
extern class UPackageTools extends UObject {

	public function SanitizePackageName(InPackageName: FString): FString;
}
