// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UParticleModuleSubUVBase")
@:include("Particles/SubUV/ParticleModuleSubUVBase.h")
extern class UParticleModuleSubUVBase extends UParticleModule {
}
