// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UParameterizeMeshToolProperties")
@:include("Properties/ParameterizeMeshProperties.h")
extern class UParameterizeMeshToolProperties extends UInteractiveToolPropertySet {
	public var Method: EParameterizeMeshUVMethod;
}
