// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URadialIntMask")
@:include("Field/FieldSystemObjects.h")
extern class URadialIntMask extends UFieldNodeInt {
	public var Radius: cpp.Float32;
	public var Position: FVector;
	public var InteriorValue: cpp.Int32;
	public var ExteriorValue: cpp.Int32;
	public var SetMaskCondition: ESetMaskConditionType;

	public function SetRadialIntMask(Radius: cpp.Float32, Position: FVector, InteriorValue: cpp.Int32, ExteriorValue: cpp.Int32, SetMaskConditionIn: ESetMaskConditionType): cpp.Star<URadialIntMask>;
}
