// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URPCDoSDetectionConfig")
@:include("Net/RPCDoSDetectionConfig.h")
extern class URPCDoSDetectionConfig extends UObject {
	public var bRPCDoSDetection: Bool;
	public var bRPCDoSAnalytics: Bool;
	public var HitchTimeQuotaMS: cpp.Int32;
	public var HitchSuspendDetectionTimeMS: cpp.Int32;
	public var DetectionSeverity: TArray<FString>;
	public var InitialConnectToleranceMS: cpp.Int32;
	public var RPCBlockWhitelist: TArray<FName>;
	public var RPCAnalyticsThresholds: TArray<FRPCAnalyticsThreshold>;
	public var RPCAnalyticsOverrideChance: cpp.Float64;
}
