// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USingleClickInputBehavior")
@:include("BaseBehaviors/SingleClickBehavior.h")
extern class USingleClickInputBehavior extends UAnyButtonInputBehavior {
	public var HitTestOnRelease: Bool;
}
