// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USkinWeightsPaintTool")
@:include("SkinWeightsPaintTool.h")
extern class USkinWeightsPaintTool extends UDynamicMeshBrushTool {
	public var ToolProps: TObjectPtr<USkinWeightsPaintToolProperties>;
}
