// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USourceEffectPhaserPreset")
@:include("SourceEffects/SourceEffectPhaser.h")
extern class USourceEffectPhaserPreset extends USoundEffectSourcePreset {
	public var Settings: FSourceEffectPhaserSettings;

	public function SetSettings(InSettings: FSourceEffectPhaserSettings): Void;
}
