// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UVoxelSolidifyMeshesToolProperties")
@:include("VoxelSolidifyMeshesTool.h")
extern class UVoxelSolidifyMeshesToolProperties extends UInteractiveToolPropertySet {
	public var WindingThreshold: cpp.Float64;
	public var ExtendBounds: cpp.Float64;
	public var SurfaceSearchSteps: cpp.Int32;
	public var bSolidAtBoundaries: Bool;
	public var bApplyThickenShells: Bool;
	public var ThickenShells: cpp.Float64;
}
