// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWorldPartitionEditorPerProjectUserSettings")
@:include("WorldPartition/WorldPartitionEditorPerProjectUserSettings.h")
extern class UWorldPartitionEditorPerProjectUserSettings extends UObject {
	public var bHideEditorDataLayers: Bool;
	public var bHideRuntimeDataLayers: Bool;
	public var bHideDataLayerActors: Bool;
	public var bHideUnloadedActors: Bool;
	public var bShowOnlySelectedActors: Bool;
	public var bHighlightSelectedDataLayers: Bool;
	public var bDisableLoadingOfLastLoadedCells: Bool;
	public var bBugItGoLoadCells: Bool;
	public var bShowCellCoords: Bool;
	public var PerWorldEditorSettings: TMap<TSoftObjectPtr<UWorld>, FWorldPartitionPerWorldSettings>;
}
