// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWeldMeshEdgesTool")
@:include("WeldMeshEdgesTool.h")
@:structAccess
extern class WeldMeshEdgesTool extends SingleSelectionMeshEditingTool {
	@:protected public var Settings: cpp.Star<WeldMeshEdgesToolProperties>;
	@:protected public var PreviewCompute: cpp.Star<MeshOpPreviewWithBackgroundCompute>;
	@:protected public var MeshElementsDisplay: cpp.Star<MeshElementsVisualizer>;
	@:protected public var OperatorFactory: cpp.Star<WeldMeshEdgesOperatorFactory>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstWeldMeshEdgesTool(WeldMeshEdgesTool) from WeldMeshEdgesTool {
}

@:forward
@:nativeGen
@:native("WeldMeshEdgesTool*")
abstract WeldMeshEdgesToolPtr(cpp.Star<WeldMeshEdgesTool>) from cpp.Star<WeldMeshEdgesTool> to cpp.Star<WeldMeshEdgesTool>{
	@:from
	public static extern inline function fromValue(v: WeldMeshEdgesTool): WeldMeshEdgesToolPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): WeldMeshEdgesTool {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}