// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWorldPartitionResaveActorsBuilder")
@:include("WorldPartition/WorldPartitionResaveActorsBuilder.h")
@:structAccess
extern class WorldPartitionResaveActorsBuilder extends WorldPartitionBuilder {
	public var ActorClassName: FString;
	public var bReportOnly: Bool;
	public var bResaveDirtyActorDescsOnly: Bool;
	public var bSwitchActorPackagingSchemeToReduced: Bool;
	public var bEnableActorFolders: Bool;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstWorldPartitionResaveActorsBuilder(WorldPartitionResaveActorsBuilder) from WorldPartitionResaveActorsBuilder {
	public extern var ActorClassName(get, never): FString;
	public inline extern function get_ActorClassName(): FString return this.ActorClassName;
	public extern var bReportOnly(get, never): Bool;
	public inline extern function get_bReportOnly(): Bool return this.bReportOnly;
	public extern var bResaveDirtyActorDescsOnly(get, never): Bool;
	public inline extern function get_bResaveDirtyActorDescsOnly(): Bool return this.bResaveDirtyActorDescsOnly;
	public extern var bSwitchActorPackagingSchemeToReduced(get, never): Bool;
	public inline extern function get_bSwitchActorPackagingSchemeToReduced(): Bool return this.bSwitchActorPackagingSchemeToReduced;
	public extern var bEnableActorFolders(get, never): Bool;
	public inline extern function get_bEnableActorFolders(): Bool return this.bEnableActorFolders;
}

@:forward
@:nativeGen
@:native("WorldPartitionResaveActorsBuilder*")
abstract WorldPartitionResaveActorsBuilderPtr(cpp.Star<WorldPartitionResaveActorsBuilder>) from cpp.Star<WorldPartitionResaveActorsBuilder> to cpp.Star<WorldPartitionResaveActorsBuilder>{
	@:from
	public static extern inline function fromValue(v: WorldPartitionResaveActorsBuilder): WorldPartitionResaveActorsBuilderPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): WorldPartitionResaveActorsBuilder {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}