// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UActorContainer")
@:include("Engine/Level.h")
@:valueType
extern class ActorContainer extends Object {
	public var Actors: TMap<FName, ucpp.Ptr<Actor>>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstActorContainer(ActorContainer) from ActorContainer {
	public extern var Actors(get, never): TMap<FName, ucpp.Ptr<Actor.ConstActor>>;
	public inline extern function get_Actors(): TMap<FName, ucpp.Ptr<Actor.ConstActor>> return this.Actors;
}

@:forward
@:nativeGen
@:native("ActorContainer*")
abstract ActorContainerPtr(ucpp.Ptr<ActorContainer>) from ucpp.Ptr<ActorContainer> to ucpp.Ptr<ActorContainer>{
	@:from
	public static extern inline function fromValue(v: ActorContainer): ActorContainerPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ActorContainer {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}