// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UActorBrowserConfig")
@:include("ActorBrowsingModeSettings.h")
@:structAccess
extern class ActorBrowserConfig extends EditorConfigBase {
	public var ActorBrowsers: TMap<FName, ActorBrowsingModeConfig>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstActorBrowserConfig(ActorBrowserConfig) from ActorBrowserConfig {
	public extern var ActorBrowsers(get, never): TMap<FName, ActorBrowsingModeConfig>;
	public inline extern function get_ActorBrowsers(): TMap<FName, ActorBrowsingModeConfig> return this.ActorBrowsers;
}

@:forward
@:nativeGen
@:native("ActorBrowserConfig*")
abstract ActorBrowserConfigPtr(cpp.Star<ActorBrowserConfig>) from cpp.Star<ActorBrowserConfig> to cpp.Star<ActorBrowserConfig>{
	@:from
	public static extern inline function fromValue(v: ActorBrowserConfig): ActorBrowserConfigPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ActorBrowserConfig {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}