// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAISightTargetInterface")
@:valueType
extern class AISightTargetInterface extends Interface {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstAISightTargetInterface(AISightTargetInterface) from AISightTargetInterface {
}

@:forward
@:nativeGen
@:native("AISightTargetInterface*")
abstract AISightTargetInterfacePtr(ucpp.Ptr<AISightTargetInterface>) from ucpp.Ptr<AISightTargetInterface> to ucpp.Ptr<AISightTargetInterface>{
	@:from
	public static extern inline function fromValue(v: AISightTargetInterface): AISightTargetInterfacePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): AISightTargetInterface {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}