// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAnimPoseEvaluationOptions")
@:include("AnimPose.h")
@:structAccess
extern class AnimPoseEvaluationOptions {
	public var EvaluationType: EAnimDataEvalType;
	public var bShouldRetarget: Bool;
	public var bExtractRootMotion: Bool;
	public var OptionalSkeletalMesh: cpp.Star<SkeletalMesh>;
	public var bRetrieveAdditiveAsFullPose: Bool;
	public var bEvaluateCurves: Bool;

	@:native("FAnimPoseEvaluationOptions") public function new();
}