// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAnimNode_SkeletalControlBase")
@:include("BoneControllers/AnimNode_SkeletalControlBase.h")
@:structAccess
extern class AnimNode_SkeletalControlBase extends AnimNode_Base {
	public var ComponentPose: ComponentSpacePoseLink;
	public var LODThreshold: cpp.Int32;
	public var ActualAlpha: cpp.Float32;
	public var AlphaInputType: EAnimAlphaInputType;
	public var bAlphaBoolEnabled: Bool;
	public var Alpha: cpp.Float32;
	public var AlphaScaleBias: InputScaleBias;
	public var AlphaBoolBlend: InputAlphaBoolBlend;
	public var AlphaCurveName: FName;
	public var AlphaScaleBiasClamp: InputScaleBiasClamp;

	@:native("FAnimNode_SkeletalControlBase") public function new();
}