// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAnimMontageFactory")
@:include("Factories/AnimMontageFactory.h")
@:valueType
extern class AnimMontageFactory extends Factory {
	public var TargetSkeleton: ucpp.Ptr<Skeleton>;
	public var SourceAnimation: ucpp.Ptr<AnimSequence>;
	public var PreviewSkeletalMesh: ucpp.Ptr<SkeletalMesh>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstAnimMontageFactory(AnimMontageFactory) from AnimMontageFactory {
	public extern var TargetSkeleton(get, never): ucpp.Ptr<Skeleton.ConstSkeleton>;
	public inline extern function get_TargetSkeleton(): ucpp.Ptr<Skeleton.ConstSkeleton> return this.TargetSkeleton;
	public extern var SourceAnimation(get, never): ucpp.Ptr<AnimSequence.ConstAnimSequence>;
	public inline extern function get_SourceAnimation(): ucpp.Ptr<AnimSequence.ConstAnimSequence> return this.SourceAnimation;
	public extern var PreviewSkeletalMesh(get, never): ucpp.Ptr<SkeletalMesh.ConstSkeletalMesh>;
	public inline extern function get_PreviewSkeletalMesh(): ucpp.Ptr<SkeletalMesh.ConstSkeletalMesh> return this.PreviewSkeletalMesh;
}

@:forward
@:nativeGen
@:native("AnimMontageFactory*")
abstract AnimMontageFactoryPtr(ucpp.Ptr<AnimMontageFactory>) from ucpp.Ptr<AnimMontageFactory> to ucpp.Ptr<AnimMontageFactory>{
	@:from
	public static extern inline function fromValue(v: AnimMontageFactory): AnimMontageFactoryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): AnimMontageFactory {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}