// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FAnimSyncMarker")
@:include("Animation/AnimTypes.h")
@:valueType
extern class AnimSyncMarker {
	public var MarkerName: FName;
	public var Time: ucpp.num.Float32;

	@:native("FAnimSyncMarker") public function new();
	@:native("FAnimSyncMarker") public static function make(MarkerName: FName, Time: ucpp.num.Float32, TrackIndex: ucpp.num.Int32, Guid: Guid): AnimSyncMarker ;
}