// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UAssetDefinition_NiagaraEffectType")
@:include("AssetDefinitions/AssetDefinition_NiagaraEffectType.h")
@:structAccess
extern class AssetDefinition_NiagaraEffectType extends AssetDefinitionDefault {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstAssetDefinition_NiagaraEffectType(AssetDefinition_NiagaraEffectType) from AssetDefinition_NiagaraEffectType {
}

@:forward
@:nativeGen
@:native("AssetDefinition_NiagaraEffectType*")
abstract AssetDefinition_NiagaraEffectTypePtr(cpp.Star<AssetDefinition_NiagaraEffectType>) from cpp.Star<AssetDefinition_NiagaraEffectType> to cpp.Star<AssetDefinition_NiagaraEffectType>{
	@:from
	public static extern inline function fromValue(v: AssetDefinition_NiagaraEffectType): AssetDefinition_NiagaraEffectTypePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): AssetDefinition_NiagaraEffectType {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}