// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBaseDynamicMeshComponent")
@:include("Components/BaseDynamicMeshComponent.h")
@:structAccess
extern class BaseDynamicMeshComp extends MeshComp {
	public var bExplicitShowWireframe: Bool;
	public var WireframeColor: LinearColor;
	public var ColorMode: EDynamicMeshComponentColorOverrideMode;
	public var ConstantColor: Color;
	public var bEnableFlatShading: Bool;
	public var bEnableViewModeOverrides: Bool;
	@:protected public var OverrideRenderMaterial: cpp.Star<MaterialInterface>;
	@:protected public var SecondaryRenderMaterial: cpp.Star<MaterialInterface>;
	public var bEnableRaytracing: Bool;
	public var BaseMaterials: TArray<cpp.Star<MaterialInterface>>;

	public function SetViewModeOverridesEnabled(bEnabled: Bool): Void;
	public function SetShadowsEnabled(bEnabled: Bool): Void;
	public function SetSecondaryRenderMaterial(Material: cpp.Star<MaterialInterface>): Void;
	public function SetSecondaryBuffersVisibility(bSetVisible: Bool): Void;
	public function SetOverrideRenderMaterial(Material: cpp.Star<MaterialInterface>): Void;
	public function SetEnableWireframeRenderPass(bEnable: Bool): Void;
	public function SetEnableRaytracing(bSetEnabled: Bool): Void;
	public function SetEnableFlatShading(bEnable: Bool): Void;
	public function SetConstantOverrideColor(NewColor: Color): Void;
	public function SetColorOverrideMode(NewMode: EDynamicMeshComponentColorOverrideMode): Void;
	public function HasOverrideRenderMaterial(k: cpp.Int32): Bool;
	public function GetViewModeOverridesEnabled(): Bool;
	public function GetShadowsEnabled(): Bool;
	public function GetSecondaryRenderMaterial(): cpp.Star<MaterialInterface>;
	public function GetSecondaryBuffersVisibility(): Bool;
	public function GetOverrideRenderMaterial(MaterialIndex: cpp.Int32): cpp.Star<MaterialInterface>;
	public function GetFlatShadingEnabled(): Bool;
	public function GetEnableWireframeRenderPass(): Bool;
	public function GetEnableRaytracing(): Bool;
	public function GetDynamicMesh(): cpp.Star<DynamicMesh>;
	public function GetConstantOverrideColor(): Color;
	public function GetColorOverrideMode(): EDynamicMeshComponentColorOverrideMode;
	public function ClearSecondaryRenderMaterial(): Void;
	public function ClearOverrideRenderMaterial(): Void;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward(
	HasOverrideRenderMaterial, GetViewModeOverridesEnabled, GetShadowsEnabled, GetSecondaryRenderMaterial, GetSecondaryBuffersVisibility,
	GetOverrideRenderMaterial, GetFlatShadingEnabled, GetEnableWireframeRenderPass, GetEnableRaytracing, GetConstantOverrideColor,
	GetColorOverrideMode
)
@:nativeGen
abstract ConstBaseDynamicMeshComp(BaseDynamicMeshComp) from BaseDynamicMeshComp {
	public extern var bExplicitShowWireframe(get, never): Bool;
	public inline extern function get_bExplicitShowWireframe(): Bool return this.bExplicitShowWireframe;
	public extern var WireframeColor(get, never): LinearColor;
	public inline extern function get_WireframeColor(): LinearColor return this.WireframeColor;
	public extern var ColorMode(get, never): EDynamicMeshComponentColorOverrideMode;
	public inline extern function get_ColorMode(): EDynamicMeshComponentColorOverrideMode return this.ColorMode;
	public extern var ConstantColor(get, never): Color;
	public inline extern function get_ConstantColor(): Color return this.ConstantColor;
	public extern var bEnableFlatShading(get, never): Bool;
	public inline extern function get_bEnableFlatShading(): Bool return this.bEnableFlatShading;
	public extern var bEnableViewModeOverrides(get, never): Bool;
	public inline extern function get_bEnableViewModeOverrides(): Bool return this.bEnableViewModeOverrides;
	public extern var bEnableRaytracing(get, never): Bool;
	public inline extern function get_bEnableRaytracing(): Bool return this.bEnableRaytracing;
	public extern var BaseMaterials(get, never): TArray<cpp.Star<MaterialInterface.ConstMaterialInterface>>;
	public inline extern function get_BaseMaterials(): TArray<cpp.Star<MaterialInterface.ConstMaterialInterface>> return this.BaseMaterials;
}

@:forward
@:nativeGen
@:native("BaseDynamicMeshComp*")
abstract BaseDynamicMeshCompPtr(cpp.Star<BaseDynamicMeshComp>) from cpp.Star<BaseDynamicMeshComp> to cpp.Star<BaseDynamicMeshComp>{
	@:from
	public static extern inline function fromValue(v: BaseDynamicMeshComp): BaseDynamicMeshCompPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): BaseDynamicMeshComp {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}