// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FBindingTargets")
@:include("Private/Tests/InputTestFramework.h")
@:structAccess
extern class BindingTargets {
	public var Started: cpp.Star<InputBindingTarget>;
	public var Ongoing: cpp.Star<InputBindingTarget>;
	public var Canceled: cpp.Star<InputBindingTarget>;
	public var Completed: cpp.Star<InputBindingTarget>;
	public var Triggered: cpp.Star<InputBindingTarget>;

	@:native("FBindingTargets") public function new();
	@:native("FBindingTargets") public static function make(Started: cpp.Star<InputBindingTarget>, Ongoing: cpp.Star<InputBindingTarget>, Canceled: cpp.Star<InputBindingTarget>, Completed: cpp.Star<InputBindingTarget>, Triggered: cpp.Star<InputBindingTarget>): BindingTargets ;
}