// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UBoolChannelEvaluatorSystem")
@:include("Systems/BoolChannelEvaluatorSystem.h")
@:valueType
extern class BoolChannelEvaluatorSystem extends MovieSceneEntitySystem {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstBoolChannelEvaluatorSystem(BoolChannelEvaluatorSystem) from BoolChannelEvaluatorSystem {
}

@:forward
@:nativeGen
@:native("BoolChannelEvaluatorSystem*")
abstract BoolChannelEvaluatorSystemPtr(ucpp.Ptr<BoolChannelEvaluatorSystem>) from ucpp.Ptr<BoolChannelEvaluatorSystem> to ucpp.Ptr<BoolChannelEvaluatorSystem>{
	@:from
	public static extern inline function fromValue(v: BoolChannelEvaluatorSystem): BoolChannelEvaluatorSystemPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): BoolChannelEvaluatorSystem {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}