// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UButtonWidgetStyle")
@:include("Framework/Styling/ButtonWidgetStyle.h")
@:structAccess
extern class ButtonWidgetStyle extends SlateWidgetStyleContainerBase {
	public var ButtonStyle: ButtonStyle;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstButtonWidgetStyle(ButtonWidgetStyle) from ButtonWidgetStyle {
	public extern var ButtonStyle(get, never): ButtonStyle;
	public inline extern function get_ButtonStyle(): ButtonStyle return this.ButtonStyle;
}

@:forward
@:nativeGen
@:native("ButtonWidgetStyle*")
abstract ButtonWidgetStylePtr(cpp.Star<ButtonWidgetStyle>) from cpp.Star<ButtonWidgetStyle> to cpp.Star<ButtonWidgetStyle>{
	@:from
	public static extern inline function fromValue(v: ButtonWidgetStyle): ButtonWidgetStylePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ButtonWidgetStyle {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}