// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UComboBoxString_OnSelectionChangedEvent__PythonCallable")
@:valueType
extern class ComboBoxString_OnSelectionChangedEvent__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstComboBoxString_OnSelectionChangedEvent__PythonCallable(ComboBoxString_OnSelectionChangedEvent__PythonCallable) from ComboBoxString_OnSelectionChangedEvent__PythonCallable {
}

@:forward
@:nativeGen
@:native("ComboBoxString_OnSelectionChangedEvent__PythonCallable*")
abstract ComboBoxString_OnSelectionChangedEvent__PythonCallablePtr(ucpp.Ptr<ComboBoxString_OnSelectionChangedEvent__PythonCallable>) from ucpp.Ptr<ComboBoxString_OnSelectionChangedEvent__PythonCallable> to ucpp.Ptr<ComboBoxString_OnSelectionChangedEvent__PythonCallable>{
	@:from
	public static extern inline function fromValue(v: ComboBoxString_OnSelectionChangedEvent__PythonCallable): ComboBoxString_OnSelectionChangedEvent__PythonCallablePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ComboBoxString_OnSelectionChangedEvent__PythonCallable {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}