// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UComboBoxKey_OnOpeningEvent__PythonCallable")
@:valueType
extern class ComboBoxKey_OnOpeningEvent__PythonCallable extends PythonCallableForDelegate {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstComboBoxKey_OnOpeningEvent__PythonCallable(ComboBoxKey_OnOpeningEvent__PythonCallable) from ComboBoxKey_OnOpeningEvent__PythonCallable {
}

@:forward
@:nativeGen
@:native("ComboBoxKey_OnOpeningEvent__PythonCallable*")
abstract ComboBoxKey_OnOpeningEvent__PythonCallablePtr(ucpp.Ptr<ComboBoxKey_OnOpeningEvent__PythonCallable>) from ucpp.Ptr<ComboBoxKey_OnOpeningEvent__PythonCallable> to ucpp.Ptr<ComboBoxKey_OnOpeningEvent__PythonCallable>{
	@:from
	public static extern inline function fromValue(v: ComboBoxKey_OnOpeningEvent__PythonCallable): ComboBoxKey_OnOpeningEvent__PythonCallablePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ComboBoxKey_OnOpeningEvent__PythonCallable {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}