// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FConstraintAndActiveChannel")
@:include("ConstraintChannel.h")
@:valueType
extern class ConstraintAndActiveChannel {
	public var Constraint: TSoftObjectPtr<TickableConstraint>;
	public var ActiveChannel: MovieSceneConstraintChannel;
	public var ConstraintCopyToSpawn: ucpp.Ptr<TickableConstraint>;

	@:native("FConstraintAndActiveChannel") public function new();
	@:native("FConstraintAndActiveChannel") public static function make(Constraint: TSoftObjectPtr<TickableConstraint>, ActiveChannel: MovieSceneConstraintChannel, ConstraintCopyToSpawn: ucpp.Ptr<TickableConstraint>): ConstraintAndActiveChannel ;
}