// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UControlRigTransformWorkflowOptions")
@:include("Units/ControlRigNodeWorkflow.h")
@:structAccess
extern class ControlRigTransformWorkflowOptions extends ControlRigWorkflowOptions {
	public var TransformType: TEnumAsByte<ERigTransformType>;

	public function ProvideWorkflows(InSubject: cpp.Star<Object.ConstObject>): TArray<RigVMUserWorkflow>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstControlRigTransformWorkflowOptions(ControlRigTransformWorkflowOptions) from ControlRigTransformWorkflowOptions {
	public extern var TransformType(get, never): TEnumAsByte<ERigTransformType>;
	public inline extern function get_TransformType(): TEnumAsByte<ERigTransformType> return this.TransformType;
}

@:forward
@:nativeGen
@:native("ControlRigTransformWorkflowOptions*")
abstract ControlRigTransformWorkflowOptionsPtr(cpp.Star<ControlRigTransformWorkflowOptions>) from cpp.Star<ControlRigTransformWorkflowOptions> to cpp.Star<ControlRigTransformWorkflowOptions>{
	@:from
	public static extern inline function fromValue(v: ControlRigTransformWorkflowOptions): ControlRigTransformWorkflowOptionsPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ControlRigTransformWorkflowOptions {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}