// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FControlRigGraphNodeContextMenuContext")
@:include("Private/Editor/ControlRigContextMenuContext.h")
@:valueType
extern class ControlRigGraphNodeContextMenuContext {
	public var Graph: ucpp.Ptr<RigVMGraph>;
	public var Node: ucpp.Ptr<RigVMNode>;
	public var Pin: ucpp.Ptr<RigVMPin>;

	@:native("FControlRigGraphNodeContextMenuContext") public function new();
	@:native("FControlRigGraphNodeContextMenuContext") public static function make(Graph: ucpp.Ptr<RigVMGraph>, Node: ucpp.Ptr<RigVMNode>, Pin: ucpp.Ptr<RigVMPin>): ControlRigGraphNodeContextMenuContext ;
}