// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDataflowBlueprintLibrary")
@:include("Dataflow/DataflowBlueprintLibrary.h")
@:structAccess
extern class DataflowBlueprintLibrary extends BlueprintFunctionLibrary {
	public function EvaluateTerminalNodeByName(Dataflow: cpp.Star<Dataflow>, TerminalNodeName: FName, ResultAsset: cpp.Star<Object>): Void;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstDataflowBlueprintLibrary(DataflowBlueprintLibrary) from DataflowBlueprintLibrary {
}

@:forward
@:nativeGen
@:native("DataflowBlueprintLibrary*")
abstract DataflowBlueprintLibraryPtr(cpp.Star<DataflowBlueprintLibrary>) from cpp.Star<DataflowBlueprintLibrary> to cpp.Star<DataflowBlueprintLibrary>{
	@:from
	public static extern inline function fromValue(v: DataflowBlueprintLibrary): DataflowBlueprintLibraryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DataflowBlueprintLibrary {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}