// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDataStream")
@:include("Iris/DataStream/DataStream.h")
@:structAccess
extern class DataStream extends Object {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstDataStream(DataStream) from DataStream {
}

@:forward
@:nativeGen
@:native("DataStream*")
abstract DataStreamPtr(cpp.Star<DataStream>) from cpp.Star<DataStream> to cpp.Star<DataStream>{
	@:from
	public static extern inline function fromValue(v: DataStream): DataStreamPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DataStream {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}