// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDataStreamDefinitions")
@:include("Iris/DataStream/DataStreamDefinitions.h")
@:structAccess
extern class DataStreamDefinitions extends Object {
	private var DataStreamDefinitions: TArray<DataStreamDefinition>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstDataStreamDefinitions(DataStreamDefinitions) from DataStreamDefinitions {
}

@:forward
@:nativeGen
@:native("DataStreamDefinitions*")
abstract DataStreamDefinitionsPtr(cpp.Star<DataStreamDefinitions>) from cpp.Star<DataStreamDefinitions> to cpp.Star<DataStreamDefinitions>{
	@:from
	public static extern inline function fromValue(v: DataStreamDefinitions): DataStreamDefinitionsPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DataStreamDefinitions {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}