// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDefaultTemplateProjectDefs")
@:include("DefaultTemplateProjectDefs.h")
@:valueType
extern class DefaultTemplateProjectDefs extends TemplateProjectDefs {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstDefaultTemplateProjectDefs(DefaultTemplateProjectDefs) from DefaultTemplateProjectDefs {
}

@:forward
@:nativeGen
@:native("DefaultTemplateProjectDefs*")
abstract DefaultTemplateProjectDefsPtr(ucpp.Ptr<DefaultTemplateProjectDefs>) from ucpp.Ptr<DefaultTemplateProjectDefs> to ucpp.Ptr<DefaultTemplateProjectDefs>{
	@:from
	public static extern inline function fromValue(v: DefaultTemplateProjectDefs): DefaultTemplateProjectDefsPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DefaultTemplateProjectDefs {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}