// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UDiscardedMemoryClassTemplate_2")
@:valueType
extern class DiscardedMemoryClassTemplate_2 extends RigVMMemoryStorage {
	public var FunctionLibrary___FootTrace_Entry_Ik_Foot_Bone: RigElementKey;
	public var FunctionLibrary___FootTrace_Return_Offset: Vector;
	public var FunctionLibrary___FootTrace_MathVectorAdd_Result: Vector;
	public var FunctionLibrary___FootTrace_GetTransform_Transform: Transform;
	public var FunctionLibrary___FootTrace_GetTransform_CachedIndex: TArray<CachedRigElement>;
	public var FunctionLibrary___FootTrace_MathFloatAdd_Result: ucpp.num.Float32;
	public var FunctionLibrary___FootTrace_MathFloatAdd_A: ucpp.num.Float32;
	public var FunctionLibrary___FootTrace_GetTransform_1_Transform: Transform;
	public var FunctionLibrary___FootTrace_GetTransform_1_CachedIndex: TArray<CachedRigElement>;
	public var FunctionLibrary___FootTrace_MathVectorAdd_A__IO: Vector;
	public var FunctionLibrary___FootTrace_MathVectorSub_Result: Vector;
	public var FunctionLibrary___FootTrace_MathVectorSub_A__IO: Vector;
	public var FunctionLibrary___FootTrace_SphereTraceByTraceChannel_bHit: Bool;
	public var FunctionLibrary___FootTrace_SphereTraceByTraceChannel_HitNormal: Vector;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstDiscardedMemoryClassTemplate_2(DiscardedMemoryClassTemplate_2) from DiscardedMemoryClassTemplate_2 {
	public extern var FunctionLibrary___FootTrace_Entry_Ik_Foot_Bone(get, never): RigElementKey;
	public inline extern function get_FunctionLibrary___FootTrace_Entry_Ik_Foot_Bone(): RigElementKey return this.FunctionLibrary___FootTrace_Entry_Ik_Foot_Bone;
	public extern var FunctionLibrary___FootTrace_Return_Offset(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_Return_Offset(): Vector return this.FunctionLibrary___FootTrace_Return_Offset;
	public extern var FunctionLibrary___FootTrace_MathVectorAdd_Result(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_MathVectorAdd_Result(): Vector return this.FunctionLibrary___FootTrace_MathVectorAdd_Result;
	public extern var FunctionLibrary___FootTrace_GetTransform_Transform(get, never): Transform;
	public inline extern function get_FunctionLibrary___FootTrace_GetTransform_Transform(): Transform return this.FunctionLibrary___FootTrace_GetTransform_Transform;
	public extern var FunctionLibrary___FootTrace_GetTransform_CachedIndex(get, never): TArray<CachedRigElement>;
	public inline extern function get_FunctionLibrary___FootTrace_GetTransform_CachedIndex(): TArray<CachedRigElement> return this.FunctionLibrary___FootTrace_GetTransform_CachedIndex;
	public extern var FunctionLibrary___FootTrace_MathFloatAdd_Result(get, never): ucpp.num.Float32;
	public inline extern function get_FunctionLibrary___FootTrace_MathFloatAdd_Result(): ucpp.num.Float32 return this.FunctionLibrary___FootTrace_MathFloatAdd_Result;
	public extern var FunctionLibrary___FootTrace_MathFloatAdd_A(get, never): ucpp.num.Float32;
	public inline extern function get_FunctionLibrary___FootTrace_MathFloatAdd_A(): ucpp.num.Float32 return this.FunctionLibrary___FootTrace_MathFloatAdd_A;
	public extern var FunctionLibrary___FootTrace_GetTransform_1_Transform(get, never): Transform;
	public inline extern function get_FunctionLibrary___FootTrace_GetTransform_1_Transform(): Transform return this.FunctionLibrary___FootTrace_GetTransform_1_Transform;
	public extern var FunctionLibrary___FootTrace_GetTransform_1_CachedIndex(get, never): TArray<CachedRigElement>;
	public inline extern function get_FunctionLibrary___FootTrace_GetTransform_1_CachedIndex(): TArray<CachedRigElement> return this.FunctionLibrary___FootTrace_GetTransform_1_CachedIndex;
	public extern var FunctionLibrary___FootTrace_MathVectorAdd_A__IO(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_MathVectorAdd_A__IO(): Vector return this.FunctionLibrary___FootTrace_MathVectorAdd_A__IO;
	public extern var FunctionLibrary___FootTrace_MathVectorSub_Result(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_MathVectorSub_Result(): Vector return this.FunctionLibrary___FootTrace_MathVectorSub_Result;
	public extern var FunctionLibrary___FootTrace_MathVectorSub_A__IO(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_MathVectorSub_A__IO(): Vector return this.FunctionLibrary___FootTrace_MathVectorSub_A__IO;
	public extern var FunctionLibrary___FootTrace_SphereTraceByTraceChannel_bHit(get, never): Bool;
	public inline extern function get_FunctionLibrary___FootTrace_SphereTraceByTraceChannel_bHit(): Bool return this.FunctionLibrary___FootTrace_SphereTraceByTraceChannel_bHit;
	public extern var FunctionLibrary___FootTrace_SphereTraceByTraceChannel_HitNormal(get, never): Vector;
	public inline extern function get_FunctionLibrary___FootTrace_SphereTraceByTraceChannel_HitNormal(): Vector return this.FunctionLibrary___FootTrace_SphereTraceByTraceChannel_HitNormal;
}

@:forward
@:nativeGen
@:native("DiscardedMemoryClassTemplate_2*")
abstract DiscardedMemoryClassTemplate_2Ptr(ucpp.Ptr<DiscardedMemoryClassTemplate_2>) from ucpp.Ptr<DiscardedMemoryClassTemplate_2> to ucpp.Ptr<DiscardedMemoryClassTemplate_2>{
	@:from
	public static extern inline function fromValue(v: DiscardedMemoryClassTemplate_2): DiscardedMemoryClassTemplate_2Ptr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): DiscardedMemoryClassTemplate_2 {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}