// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ECacheMode")
@:include("Chaos/CacheManagerActor.h")
extern class ECacheMode {
	static var None: ECacheMode;
	static var Play: ECacheMode;
	static var Record: ECacheMode;
	static var ECacheMode_MAX: ECacheMode;
}