// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EClassViewerDeveloperType")
@:include("Settings/ClassViewerSettings.h")
extern class EClassViewerDeveloperType {
	static var CVDT_None: EClassViewerDeveloperType;
	static var CVDT_CurrentUser: EClassViewerDeveloperType;
	static var CVDT_All: EClassViewerDeveloperType;
	static var CVDT_Max: EClassViewerDeveloperType;
	static var CVDT_MAX: EClassViewerDeveloperType;
}