// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EDistributionVectorMirrorFlags")
@:include("Distributions/DistributionVector.h")
extern class EDistributionVectorMirrorFlags {
	static var EDVMF_Same: EDistributionVectorMirrorFlags;
	static var EDVMF_Different: EDistributionVectorMirrorFlags;
	static var EDVMF_Mirror: EDistributionVectorMirrorFlags;
	static var EDVMF_MAX: EDistributionVectorMirrorFlags;
}