// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EFilterInterpolationType")
@:include("Engine/EngineTypes.h")
extern class EFilterInterpolationType {
	static var BSIT_Average: EFilterInterpolationType;
	static var BSIT_Linear: EFilterInterpolationType;
	static var BSIT_Cubic: EFilterInterpolationType;
	static var BSIT_EaseInOut: EFilterInterpolationType;
	static var BSIT_ExponentialDecay: EFilterInterpolationType;
	static var BSIT_SpringDamper: EFilterInterpolationType;
	static var BSIT_MAX: EFilterInterpolationType;
}