// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EHoleFillOpFillType")
@:include("CleaningOps/HoleFillOp.h")
extern class EHoleFillOpFillType {
	static var TriangleFan: EHoleFillOpFillType;
	static var PolygonEarClipping: EHoleFillOpFillType;
	static var Planar: EHoleFillOpFillType;
	static var Minimal: EHoleFillOpFillType;
	static var Smooth: EHoleFillOpFillType;
	static var EHoleFillOpFillType_MAX: EHoleFillOpFillType;
}