// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EInterchangeTranslatorAssetType")
@:include("InterchangeTranslatorBase.h")
extern class EInterchangeTranslatorAssetType {
	static var None: EInterchangeTranslatorAssetType;
	static var Textures: EInterchangeTranslatorAssetType;
	static var Materials: EInterchangeTranslatorAssetType;
	static var Meshes: EInterchangeTranslatorAssetType;
	static var Animations: EInterchangeTranslatorAssetType;
	static var EInterchangeTranslatorAssetType_MAX: EInterchangeTranslatorAssetType;
}