// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ELevelViewportType")
@:include("Editor/UnrealEdTypes.h")
extern class ELevelViewportType {
	static var LVT_OrthoXY: ELevelViewportType;
	static var LVT_OrthoXZ: ELevelViewportType;
	static var LVT_OrthoYZ: ELevelViewportType;
	static var LVT_Perspective: ELevelViewportType;
	static var LVT_OrthoFreelook: ELevelViewportType;
	static var LVT_OrthoNegativeXY: ELevelViewportType;
	static var LVT_OrthoNegativeXZ: ELevelViewportType;
	static var LVT_OrthoNegativeYZ: ELevelViewportType;
	static var LVT_MAX: ELevelViewportType;
	static var LVT_None: ELevelViewportType;
}