// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EMaterialPositionTransformSource")
@:include("Materials/MaterialExpressionTransformPosition.h")
extern class EMaterialPositionTransformSource {
	static var TRANSFORMPOSSOURCE_Local: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_World: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_TranslatedWorld: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_View: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_Camera: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_Particle: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_Instance: EMaterialPositionTransformSource;
	static var TRANSFORMPOSSOURCE_MAX: EMaterialPositionTransformSource;
}