// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EMotionExtractor_MotionType")
@:include("MotionExtractorTypes.h")
extern class EMotionExtractor_MotionType {
	static var Translation: EMotionExtractor_MotionType;
	static var Rotation: EMotionExtractor_MotionType;
	static var Scale: EMotionExtractor_MotionType;
	static var TranslationSpeed: EMotionExtractor_MotionType;
	static var RotationSpeed: EMotionExtractor_MotionType;
	static var EMotionExtractor_MAX: EMotionExtractor_MotionType;
}