// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EPhysicsAssetEditorCollisionViewMode")
@:include("Preferences/PhysicsAssetEditorOptions.h")
extern class EPhysicsAssetEditorCollisionViewMode {
	static var Solid: EPhysicsAssetEditorCollisionViewMode;
	static var Wireframe: EPhysicsAssetEditorCollisionViewMode;
	static var SolidWireframe: EPhysicsAssetEditorCollisionViewMode;
	static var None: EPhysicsAssetEditorCollisionViewMode;
	static var EPhysicsAssetEditorCollisionViewMode_MAX: EPhysicsAssetEditorCollisionViewMode;
}