// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ETrail2SourceMethod")
@:include("Particles/Trail/ParticleModuleTrailSource.h")
extern class ETrail2SourceMethod {
	static var PET2SRCM_Default: ETrail2SourceMethod;
	static var PET2SRCM_Particle: ETrail2SourceMethod;
	static var PET2SRCM_Actor: ETrail2SourceMethod;
	static var PET2SRCM_MAX: ETrail2SourceMethod;
}