// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("EVirtualKeyboardDismissAction")
@:include("Widgets/Text/ISlateEditableTextWidget.h")
extern class EVirtualKeyboardDismissAction {
	static var TextChangeOnDismiss: EVirtualKeyboardDismissAction;
	static var TextCommitOnAccept: EVirtualKeyboardDismissAction;
	static var TextCommitOnDismiss: EVirtualKeyboardDismissAction;
	static var EVirtualKeyboardDismissAction_MAX: EVirtualKeyboardDismissAction;
}