// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UFractureToolAddEmbeddedGeometry")
@:include("FractureToolEmbed.h")
@:valueType
extern class FractureToolAddEmbeddedGeometry extends FractureActionTool {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstFractureToolAddEmbeddedGeometry(FractureToolAddEmbeddedGeometry) from FractureToolAddEmbeddedGeometry {
}

@:forward
@:nativeGen
@:native("FractureToolAddEmbeddedGeometry*")
abstract FractureToolAddEmbeddedGeometryPtr(ucpp.Ptr<FractureToolAddEmbeddedGeometry>) from ucpp.Ptr<FractureToolAddEmbeddedGeometry> to ucpp.Ptr<FractureToolAddEmbeddedGeometry>{
	@:from
	public static extern inline function fromValue(v: FractureToolAddEmbeddedGeometry): FractureToolAddEmbeddedGeometryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): FractureToolAddEmbeddedGeometry {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}