// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FGameplayDebuggerCategoryConfig")
@:include("GameplayDebuggerConfig.h")
@:valueType
extern class GameplayDebuggerCategoryConfig {
	public var CategoryName: FString;
	public var SlotIdx: ucpp.num.Int32;
	public var ActiveInGame: EGameplayDebuggerOverrideMode;
	public var ActiveInSimulate: EGameplayDebuggerOverrideMode;
	public var Hidden: EGameplayDebuggerOverrideMode;
	public var bOverrideSlotIdx: Bool;
	public var InputHandlers: TArray<GameplayDebuggerInputConfig>;

	@:native("FGameplayDebuggerCategoryConfig") public function new();
}