// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UGizmoNilStateTarget")
@:include("BaseGizmos/StateTargets.h")
@:valueType
extern class GizmoNilStateTarget extends Object {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstGizmoNilStateTarget(GizmoNilStateTarget) from GizmoNilStateTarget {
}

@:forward
@:nativeGen
@:native("GizmoNilStateTarget*")
abstract GizmoNilStateTargetPtr(ucpp.Ptr<GizmoNilStateTarget>) from ucpp.Ptr<GizmoNilStateTarget> to ucpp.Ptr<GizmoNilStateTarget>{
	@:from
	public static extern inline function fromValue(v: GizmoNilStateTarget): GizmoNilStateTargetPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): GizmoNilStateTarget {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}