// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UInterchangeDirectionalLightFactoryNode")
@:include("InterchangeLightFactoryNode.h")
@:valueType
extern class InterchangeDirectionalLightFactoryNode extends InterchangeBaseLightFactoryNode {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstInterchangeDirectionalLightFactoryNode(InterchangeDirectionalLightFactoryNode) from InterchangeDirectionalLightFactoryNode {
}

@:forward
@:nativeGen
@:native("InterchangeDirectionalLightFactoryNode*")
abstract InterchangeDirectionalLightFactoryNodePtr(ucpp.Ptr<InterchangeDirectionalLightFactoryNode>) from ucpp.Ptr<InterchangeDirectionalLightFactoryNode> to ucpp.Ptr<InterchangeDirectionalLightFactoryNode>{
	@:from
	public static extern inline function fromValue(v: InterchangeDirectionalLightFactoryNode): InterchangeDirectionalLightFactoryNodePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): InterchangeDirectionalLightFactoryNode {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}