// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMaterialAttributesInput")
@:include("Materials/MaterialExpression.h")
@:valueType
extern class MaterialAttributesInput extends ExpressionInput {
	public var PropertyConnectedBitmask: ucpp.num.Int32;

	@:native("FMaterialAttributesInput") public function new();
	@:native("FMaterialAttributesInput") public static function make(PropertyConnectedBitmask: ucpp.num.Int32): MaterialAttributesInput ;
}