// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionSingleLayerWaterMaterialOutput")
@:include("Materials/MaterialExpressionSingleLayerWaterMaterialOutput.h")
@:valueType
extern class MaterialExpressionSingleLayerWaterMaterialOutput extends MaterialExpressionCustomOutput {
	public var ScatteringCoefficients: ExpressionInput;
	public var AbsorptionCoefficients: ExpressionInput;
	public var PhaseG: ExpressionInput;
	public var ColorScaleBehindWater: ExpressionInput;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstMaterialExpressionSingleLayerWaterMaterialOutput(MaterialExpressionSingleLayerWaterMaterialOutput) from MaterialExpressionSingleLayerWaterMaterialOutput {
	public extern var ScatteringCoefficients(get, never): ExpressionInput;
	public inline extern function get_ScatteringCoefficients(): ExpressionInput return this.ScatteringCoefficients;
	public extern var AbsorptionCoefficients(get, never): ExpressionInput;
	public inline extern function get_AbsorptionCoefficients(): ExpressionInput return this.AbsorptionCoefficients;
	public extern var PhaseG(get, never): ExpressionInput;
	public inline extern function get_PhaseG(): ExpressionInput return this.PhaseG;
	public extern var ColorScaleBehindWater(get, never): ExpressionInput;
	public inline extern function get_ColorScaleBehindWater(): ExpressionInput return this.ColorScaleBehindWater;
}

@:forward
@:nativeGen
@:native("MaterialExpressionSingleLayerWaterMaterialOutput*")
abstract MaterialExpressionSingleLayerWaterMaterialOutputPtr(ucpp.Ptr<MaterialExpressionSingleLayerWaterMaterialOutput>) from ucpp.Ptr<MaterialExpressionSingleLayerWaterMaterialOutput> to ucpp.Ptr<MaterialExpressionSingleLayerWaterMaterialOutput>{
	@:from
	public static extern inline function fromValue(v: MaterialExpressionSingleLayerWaterMaterialOutput): MaterialExpressionSingleLayerWaterMaterialOutputPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MaterialExpressionSingleLayerWaterMaterialOutput {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}