// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMaterialExpressionFloor")
@:include("Materials/MaterialExpressionFloor.h")
@:valueType
extern class MaterialExpressionFloor extends MaterialExpression {
	public var Input: ExpressionInput;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstMaterialExpressionFloor(MaterialExpressionFloor) from MaterialExpressionFloor {
	public extern var Input(get, never): ExpressionInput;
	public inline extern function get_Input(): ExpressionInput return this.Input;
}

@:forward
@:nativeGen
@:native("MaterialExpressionFloor*")
abstract MaterialExpressionFloorPtr(ucpp.Ptr<MaterialExpressionFloor>) from ucpp.Ptr<MaterialExpressionFloor> to ucpp.Ptr<MaterialExpressionFloor>{
	@:from
	public static extern inline function fromValue(v: MaterialExpressionFloor): MaterialExpressionFloorPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MaterialExpressionFloor {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}