// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMetasoundEditorGraphMemberDefaultFloatArray")
@:include("MetasoundEditorGraphMemberDefaults.h")
@:valueType
extern class MetasoundEditorGraphMemberDefaultFloatArray extends MetasoundEditorGraphMemberDefaultLiteral {
	public var Default: TArray<ucpp.num.Float32>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstMetasoundEditorGraphMemberDefaultFloatArray(MetasoundEditorGraphMemberDefaultFloatArray) from MetasoundEditorGraphMemberDefaultFloatArray {
	public extern var Default(get, never): TArray<ucpp.num.Float32>;
	public inline extern function get_Default(): TArray<ucpp.num.Float32> return this.Default;
}

@:forward
@:nativeGen
@:native("MetasoundEditorGraphMemberDefaultFloatArray*")
abstract MetasoundEditorGraphMemberDefaultFloatArrayPtr(ucpp.Ptr<MetasoundEditorGraphMemberDefaultFloatArray>) from ucpp.Ptr<MetasoundEditorGraphMemberDefaultFloatArray> to ucpp.Ptr<MetasoundEditorGraphMemberDefaultFloatArray>{
	@:from
	public static extern inline function fromValue(v: MetasoundEditorGraphMemberDefaultFloatArray): MetasoundEditorGraphMemberDefaultFloatArrayPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MetasoundEditorGraphMemberDefaultFloatArray {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}