// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieScene3DAttachTrackRecorder")
@:include("TrackRecorders/MovieScene3DAttachTrackRecorder.h")
@:structAccess
extern class MovieScene3DAttachTrackRecorder extends MovieSceneTrackRecorder {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieScene3DAttachTrackRecorder(MovieScene3DAttachTrackRecorder) from MovieScene3DAttachTrackRecorder {
}

@:forward
@:nativeGen
@:native("MovieScene3DAttachTrackRecorder*")
abstract MovieScene3DAttachTrackRecorderPtr(cpp.Star<MovieScene3DAttachTrackRecorder>) from cpp.Star<MovieScene3DAttachTrackRecorder> to cpp.Star<MovieScene3DAttachTrackRecorder>{
	@:from
	public static extern inline function fromValue(v: MovieScene3DAttachTrackRecorder): MovieScene3DAttachTrackRecorderPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MovieScene3DAttachTrackRecorder {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}