// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FMovieSceneToolsFbxSettings")
@:include("MovieSceneToolsProjectSettings.h")
@:valueType
extern class MovieSceneToolsFbxSettings {
	public var FbxPropertyName: FString;
	public var PropertyPath: MovieSceneToolsPropertyTrackSettings;
	public var PropertyType: EMovieSceneToolsPropertyTrackType;

	@:native("FMovieSceneToolsFbxSettings") public function new();
	@:native("FMovieSceneToolsFbxSettings") public static function make(FbxPropertyName: FString, PropertyPath: MovieSceneToolsPropertyTrackSettings, PropertyType: EMovieSceneToolsPropertyTrackType): MovieSceneToolsFbxSettings ;
}