// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UMovieSceneSubTrack")
@:include("Tracks/MovieSceneSubTrack.h")
@:structAccess
extern class MovieSceneSubTrack extends MovieSceneNameableTrack {
	@:protected public var Sections: TArray<cpp.Star<MovieSceneSection>>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstMovieSceneSubTrack(MovieSceneSubTrack) from MovieSceneSubTrack {
}

@:forward
@:nativeGen
@:native("MovieSceneSubTrack*")
abstract MovieSceneSubTrackPtr(cpp.Star<MovieSceneSubTrack>) from cpp.Star<MovieSceneSubTrack> to cpp.Star<MovieSceneSubTrack>{
	@:from
	public static extern inline function fromValue(v: MovieSceneSubTrack): MovieSceneSubTrackPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): MovieSceneSubTrack {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}