// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("ANavSystemConfigOverride")
@:include("NavSystemConfigOverride.h")
@:structAccess
extern class NavSystemConfigOverride extends Actor {
	@:protected public var NavigationSystemConfig: cpp.Star<NavigationSystemConfig>;
	@:protected public var OverridePolicy: ENavSystemOverridePolicy;
	@:protected public var bLoadOnClient: Bool;

	public function ApplyChanges(): Void;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstNavSystemConfigOverride(NavSystemConfigOverride) from NavSystemConfigOverride {
}

@:forward
@:nativeGen
@:native("NavSystemConfigOverride*")
abstract NavSystemConfigOverridePtr(cpp.Star<NavSystemConfigOverride>) from cpp.Star<NavSystemConfigOverride> to cpp.Star<NavSystemConfigOverride>{
	@:from
	public static extern inline function fromValue(v: NavSystemConfigOverride): NavSystemConfigOverridePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): NavSystemConfigOverride {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}