// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraDataInterfaceAudioSubmix")
@:include("NiagaraDataInterfaceAudio.h")
@:structAccess
extern class NiagaraDataInterfaceAudioSubmix extends NiagaraDataInterface {
	public var Submix: cpp.Star<SoundSubmix>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstNiagaraDataInterfaceAudioSubmix(NiagaraDataInterfaceAudioSubmix) from NiagaraDataInterfaceAudioSubmix {
	public extern var Submix(get, never): cpp.Star<SoundSubmix.ConstSoundSubmix>;
	public inline extern function get_Submix(): cpp.Star<SoundSubmix.ConstSoundSubmix> return this.Submix;
}

@:forward
@:nativeGen
@:native("NiagaraDataInterfaceAudioSubmix*")
abstract NiagaraDataInterfaceAudioSubmixPtr(cpp.Star<NiagaraDataInterfaceAudioSubmix>) from cpp.Star<NiagaraDataInterfaceAudioSubmix> to cpp.Star<NiagaraDataInterfaceAudioSubmix>{
	@:from
	public static extern inline function fromValue(v: NiagaraDataInterfaceAudioSubmix): NiagaraDataInterfaceAudioSubmixPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): NiagaraDataInterfaceAudioSubmix {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}