// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraSystemAuditCommandlet")
@:include("Commandlets/NiagaraSystemAuditCommandlet.h")
@:structAccess
extern class NiagaraSystemAuditCommandlet extends Commandlet {
	public var PackagesToSave: TArray<cpp.Star<Package>>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstNiagaraSystemAuditCommandlet(NiagaraSystemAuditCommandlet) from NiagaraSystemAuditCommandlet {
	public extern var PackagesToSave(get, never): TArray<cpp.Star<Package.ConstPackage>>;
	public inline extern function get_PackagesToSave(): TArray<cpp.Star<Package.ConstPackage>> return this.PackagesToSave;
}

@:forward
@:nativeGen
@:native("NiagaraSystemAuditCommandlet*")
abstract NiagaraSystemAuditCommandletPtr(cpp.Star<NiagaraSystemAuditCommandlet>) from cpp.Star<NiagaraSystemAuditCommandlet> to cpp.Star<NiagaraSystemAuditCommandlet>{
	@:from
	public static extern inline function fromValue(v: NiagaraSystemAuditCommandlet): NiagaraSystemAuditCommandletPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): NiagaraSystemAuditCommandlet {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}