// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FNiagaraScriptExecutionParameterStore")
@:include("NiagaraScriptExecutionParameterStore.h")
@:structAccess
extern class NiagaraScriptExecutionParameterStore extends NiagaraParameterStore {
	public var ParameterSize: cpp.Int32;
	public var PaddedParameterSize: cpp.UInt32;
	public var PaddingInfo: TArray<NiagaraScriptExecutionPaddingInfo>;
	public var bInitialized: Bool;

	@:native("FNiagaraScriptExecutionParameterStore") public function new();
	@:native("FNiagaraScriptExecutionParameterStore") public static function make(ParameterSize: cpp.Int32, PaddedParameterSize: cpp.UInt32, PaddingInfo: TArray<NiagaraScriptExecutionPaddingInfo>, bInitialized: Bool): NiagaraScriptExecutionParameterStore ;
}