// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraStackModuleItemLinkedInputCollection")
@:include("ViewModels/Stack/NiagaraStackModuleItemLinkedInputCollection.h")
@:valueType
extern class NiagaraStackModuleItemLinkedInputCollection extends NiagaraStackEntry {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstNiagaraStackModuleItemLinkedInputCollection(NiagaraStackModuleItemLinkedInputCollection) from NiagaraStackModuleItemLinkedInputCollection {
}

@:forward
@:nativeGen
@:native("NiagaraStackModuleItemLinkedInputCollection*")
abstract NiagaraStackModuleItemLinkedInputCollectionPtr(ucpp.Ptr<NiagaraStackModuleItemLinkedInputCollection>) from ucpp.Ptr<NiagaraStackModuleItemLinkedInputCollection> to ucpp.Ptr<NiagaraStackModuleItemLinkedInputCollection>{
	@:from
	public static extern inline function fromValue(v: NiagaraStackModuleItemLinkedInputCollection): NiagaraStackModuleItemLinkedInputCollectionPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): NiagaraStackModuleItemLinkedInputCollection {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}