// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UNiagaraMergeable")
@:include("NiagaraMergeable.h")
@:structAccess
extern class NiagaraMergeable extends Object {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstNiagaraMergeable(NiagaraMergeable) from NiagaraMergeable {
}

@:forward
@:nativeGen
@:native("NiagaraMergeable*")
abstract NiagaraMergeablePtr(cpp.Star<NiagaraMergeable>) from cpp.Star<NiagaraMergeable> to cpp.Star<NiagaraMergeable>{
	@:from
	public static extern inline function fromValue(v: NiagaraMergeable): NiagaraMergeablePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): NiagaraMergeable {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}