// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPaperSpriteSheetImportFactory")
@:include("PaperSpriteSheetImportFactory.h")
@:valueType
extern class PaperSpriteSheetImportFactory extends Factory {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstPaperSpriteSheetImportFactory(PaperSpriteSheetImportFactory) from PaperSpriteSheetImportFactory {
}

@:forward
@:nativeGen
@:native("PaperSpriteSheetImportFactory*")
abstract PaperSpriteSheetImportFactoryPtr(ucpp.Ptr<PaperSpriteSheetImportFactory>) from ucpp.Ptr<PaperSpriteSheetImportFactory> to ucpp.Ptr<PaperSpriteSheetImportFactory>{
	@:from
	public static extern inline function fromValue(v: PaperSpriteSheetImportFactory): PaperSpriteSheetImportFactoryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): PaperSpriteSheetImportFactory {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}