// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UPhysicsFieldStatics")
@:include("PhysicsField/PhysicsFieldComponent.h")
@:valueType
extern class PhysicsFieldStatics extends BlueprintFunctionLibrary {
	public function EvalPhysicsVectorField(WorldContextObject: ucpp.Ptr<Object.ConstObject>, WorldPosition: ucpp.Ref<Vector>, VectorType: TEnumAsByte<EFieldVectorType>): Vector;
	public function EvalPhysicsScalarField(WorldContextObject: ucpp.Ptr<Object.ConstObject>, WorldPosition: ucpp.Ref<Vector>, ScalarType: TEnumAsByte<EFieldScalarType>): ucpp.num.Float32;
	public function EvalPhysicsIntegerField(WorldContextObject: ucpp.Ptr<Object.ConstObject>, WorldPosition: ucpp.Ref<Vector>, IntegerType: TEnumAsByte<EFieldIntegerType>): ucpp.num.Int32;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstPhysicsFieldStatics(PhysicsFieldStatics) from PhysicsFieldStatics {
}

@:forward
@:nativeGen
@:native("PhysicsFieldStatics*")
abstract PhysicsFieldStaticsPtr(ucpp.Ptr<PhysicsFieldStatics>) from ucpp.Ptr<PhysicsFieldStatics> to ucpp.Ptr<PhysicsFieldStatics>{
	@:from
	public static extern inline function fromValue(v: PhysicsFieldStatics): PhysicsFieldStaticsPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): PhysicsFieldStatics {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}