// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FPlateCropSettings")
@:include("CineCameraSettings.h")
@:valueType
extern class PlateCropSettings {
	public var AspectRatio: ucpp.num.Float32;

	@:native("FPlateCropSettings") public function new();
	@:native("FPlateCropSettings") public static function make(AspectRatio: ucpp.num.Float32): PlateCropSettings ;
}