// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URadialVector")
@:include("Field/FieldSystemObjects.h")
@:structAccess
extern class RadialVector extends FieldNodeVector {
	public var Magnitude: cpp.Float32;
	public var Position: Vector;

	public function SetRadialVector(Magnitude: cpp.Float32, Position: Vector): cpp.Star<RadialVector>;

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstRadialVector(RadialVector) from RadialVector {
	public extern var Magnitude(get, never): cpp.Float32;
	public inline extern function get_Magnitude(): cpp.Float32 return this.Magnitude;
	public extern var Position(get, never): Vector;
	public inline extern function get_Position(): Vector return this.Position;
}

@:forward
@:nativeGen
@:native("RadialVector*")
abstract RadialVectorPtr(cpp.Star<RadialVector>) from cpp.Star<RadialVector> to cpp.Star<RadialVector>{
	@:from
	public static extern inline function fromValue(v: RadialVector): RadialVectorPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): RadialVector {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}