// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AReflectionCapture")
@:include("Engine/ReflectionCapture.h")
@:valueType
extern class ReflectionCapture extends Actor {
	private var CaptureComponent: ucpp.Ptr<ReflectionCaptureComp>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstReflectionCapture(ReflectionCapture) from ReflectionCapture {
}

@:forward
@:nativeGen
@:native("ReflectionCapture*")
abstract ReflectionCapturePtr(ucpp.Ptr<ReflectionCapture>) from ucpp.Ptr<ReflectionCapture> to ucpp.Ptr<ReflectionCapture>{
	@:from
	public static extern inline function fromValue(v: ReflectionCapture): ReflectionCapturePtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ReflectionCapture {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}