// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UReimportCurveFactory")
@:include("Factories/ReimportCurveFactory.h")
@:valueType
extern class ReimportCurveFactory extends CSVImportFactory {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstReimportCurveFactory(ReimportCurveFactory) from ReimportCurveFactory {
}

@:forward
@:nativeGen
@:native("ReimportCurveFactory*")
abstract ReimportCurveFactoryPtr(ucpp.Ptr<ReimportCurveFactory>) from ucpp.Ptr<ReimportCurveFactory> to ucpp.Ptr<ReimportCurveFactory>{
	@:from
	public static extern inline function fromValue(v: ReimportCurveFactory): ReimportCurveFactoryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): ReimportCurveFactory {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}