// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URetriangulateGeometrySelectionCommand")
@:include("Commands/RetriangulateGeometrySelectionCommand.h")
@:structAccess
extern class RetriangulateGeometrySelectionCommand extends GeometrySelectionEditCommand {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstRetriangulateGeometrySelectionCommand(RetriangulateGeometrySelectionCommand) from RetriangulateGeometrySelectionCommand {
}

@:forward
@:nativeGen
@:native("RetriangulateGeometrySelectionCommand*")
abstract RetriangulateGeometrySelectionCommandPtr(cpp.Star<RetriangulateGeometrySelectionCommand>) from cpp.Star<RetriangulateGeometrySelectionCommand> to cpp.Star<RetriangulateGeometrySelectionCommand>{
	@:from
	public static extern inline function fromValue(v: RetriangulateGeometrySelectionCommand): RetriangulateGeometrySelectionCommandPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): RetriangulateGeometrySelectionCommand {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}