// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("URigVMBlueprintGeneratedClass")
@:include("RigVMBlueprintGeneratedClass.h")
@:valueType
extern class RigVMBlueprintGeneratedClass extends BlueprintGeneratedClass {
	public var GraphFunctionStore: RigVMGraphFunctionStore;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstRigVMBlueprintGeneratedClass(RigVMBlueprintGeneratedClass) from RigVMBlueprintGeneratedClass {
	public extern var GraphFunctionStore(get, never): RigVMGraphFunctionStore;
	public inline extern function get_GraphFunctionStore(): RigVMGraphFunctionStore return this.GraphFunctionStore;
}

@:forward
@:nativeGen
@:native("RigVMBlueprintGeneratedClass*")
abstract RigVMBlueprintGeneratedClassPtr(ucpp.Ptr<RigVMBlueprintGeneratedClass>) from ucpp.Ptr<RigVMBlueprintGeneratedClass> to ucpp.Ptr<RigVMBlueprintGeneratedClass>{
	@:from
	public static extern inline function fromValue(v: RigVMBlueprintGeneratedClass): RigVMBlueprintGeneratedClassPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): RigVMBlueprintGeneratedClass {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}