// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("USoundNodeDelay")
@:include("Sound/SoundNodeDelay.h")
@:valueType
extern class SoundNodeDelay extends SoundNode {
	public var DelayMin: ucpp.num.Float32;
	public var DelayMax: ucpp.num.Float32;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstSoundNodeDelay(SoundNodeDelay) from SoundNodeDelay {
	public extern var DelayMin(get, never): ucpp.num.Float32;
	public inline extern function get_DelayMin(): ucpp.num.Float32 return this.DelayMin;
	public extern var DelayMax(get, never): ucpp.num.Float32;
	public inline extern function get_DelayMax(): ucpp.num.Float32 return this.DelayMax;
}

@:forward
@:nativeGen
@:native("SoundNodeDelay*")
abstract SoundNodeDelayPtr(ucpp.Ptr<SoundNodeDelay>) from ucpp.Ptr<SoundNodeDelay> to ucpp.Ptr<SoundNodeDelay>{
	@:from
	public static extern inline function fromValue(v: SoundNodeDelay): SoundNodeDelayPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): SoundNodeDelay {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}