// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FStaticMeshReductionOptions")
@:include("StaticMeshEditorSubsystemHelpers.h")
@:structAccess
extern class StaticMeshReductionOptions {
	public var bAutoComputeLODScreenSize: Bool;
	public var ReductionSettings: TArray<StaticMeshReductionSettings>;

	@:native("FStaticMeshReductionOptions") public function new();
	@:native("FStaticMeshReductionOptions") public static function make(bAutoComputeLODScreenSize: Bool, ReductionSettings: TArray<StaticMeshReductionSettings>): StaticMeshReductionOptions ;
}