// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FStaticMeshReductionSettings")
@:include("StaticMeshEditorSubsystemHelpers.h")
@:valueType
extern class StaticMeshReductionSettings {
	public var PercentTriangles: ucpp.num.Float32;
	public var ScreenSize: ucpp.num.Float32;

	@:native("FStaticMeshReductionSettings") public function new();
	@:native("FStaticMeshReductionSettings") public static function make(PercentTriangles: ucpp.num.Float32, ScreenSize: ucpp.num.Float32): StaticMeshReductionSettings ;
}