// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FTimespan")
@:include("UObject/NoExportTypes.h")
@:structAccess
extern class Timespan {
	@:native("FTimespan") public function new();
}