// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("AVariantManagerTestActor")
@:include("VariantManagerTestActor.h")
@:valueType
extern class VariantManagerTestActor extends Actor {
	public var EnumWithNoDefault: EVariantManagerTestEnum;
	public var EnumWithSecondDefault: EVariantManagerTestEnum;
	public var CapturedByteProperty: ucpp.num.UInt8;
	public var CapturedIntProperty: ucpp.num.Int32;
	public var CapturedFloatProperty: ucpp.num.Float32;
	public var bCapturedBoolProperty: Bool;
	public var CapturedObjectProperty: ucpp.Ptr<Object>;
	public var CapturedInterfaceProperty: Interface;
	public var CapturedNameProperty: FName;
	public var CapturedStrProperty: FString;
	public var CapturedTextProperty: FText;
	public var CapturedRotatorProperty: Rotator;
	public var CapturedColorProperty: Color;
	public var CapturedLinearColorProperty: LinearColor;
	public var CapturedVectorProperty: Vector;
	public var CapturedQuatProperty: Quat;
	public var CapturedVector4Property: Vector4;
	public var CapturedVector2DProperty: Vector2D;
	public var CapturedIntPointProperty: IntPoint;
	public var CapturedUObjectArrayProperty: TArray<ucpp.Ptr<Object>>;
	public var CapturedVectorArrayProperty: TArray<Vector>;

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstVariantManagerTestActor(VariantManagerTestActor) from VariantManagerTestActor {
	public extern var EnumWithNoDefault(get, never): EVariantManagerTestEnum;
	public inline extern function get_EnumWithNoDefault(): EVariantManagerTestEnum return this.EnumWithNoDefault;
	public extern var EnumWithSecondDefault(get, never): EVariantManagerTestEnum;
	public inline extern function get_EnumWithSecondDefault(): EVariantManagerTestEnum return this.EnumWithSecondDefault;
	public extern var CapturedByteProperty(get, never): ucpp.num.UInt8;
	public inline extern function get_CapturedByteProperty(): ucpp.num.UInt8 return this.CapturedByteProperty;
	public extern var CapturedIntProperty(get, never): ucpp.num.Int32;
	public inline extern function get_CapturedIntProperty(): ucpp.num.Int32 return this.CapturedIntProperty;
	public extern var CapturedFloatProperty(get, never): ucpp.num.Float32;
	public inline extern function get_CapturedFloatProperty(): ucpp.num.Float32 return this.CapturedFloatProperty;
	public extern var bCapturedBoolProperty(get, never): Bool;
	public inline extern function get_bCapturedBoolProperty(): Bool return this.bCapturedBoolProperty;
	public extern var CapturedObjectProperty(get, never): ucpp.Ptr<Object.ConstObject>;
	public inline extern function get_CapturedObjectProperty(): ucpp.Ptr<Object.ConstObject> return this.CapturedObjectProperty;
	public extern var CapturedInterfaceProperty(get, never): Interface.ConstInterface;
	public inline extern function get_CapturedInterfaceProperty(): Interface.ConstInterface return this.CapturedInterfaceProperty;
	public extern var CapturedNameProperty(get, never): FName;
	public inline extern function get_CapturedNameProperty(): FName return this.CapturedNameProperty;
	public extern var CapturedStrProperty(get, never): FString;
	public inline extern function get_CapturedStrProperty(): FString return this.CapturedStrProperty;
	public extern var CapturedTextProperty(get, never): FText;
	public inline extern function get_CapturedTextProperty(): FText return this.CapturedTextProperty;
	public extern var CapturedRotatorProperty(get, never): Rotator;
	public inline extern function get_CapturedRotatorProperty(): Rotator return this.CapturedRotatorProperty;
	public extern var CapturedColorProperty(get, never): Color;
	public inline extern function get_CapturedColorProperty(): Color return this.CapturedColorProperty;
	public extern var CapturedLinearColorProperty(get, never): LinearColor;
	public inline extern function get_CapturedLinearColorProperty(): LinearColor return this.CapturedLinearColorProperty;
	public extern var CapturedVectorProperty(get, never): Vector;
	public inline extern function get_CapturedVectorProperty(): Vector return this.CapturedVectorProperty;
	public extern var CapturedQuatProperty(get, never): Quat;
	public inline extern function get_CapturedQuatProperty(): Quat return this.CapturedQuatProperty;
	public extern var CapturedVector4Property(get, never): Vector4;
	public inline extern function get_CapturedVector4Property(): Vector4 return this.CapturedVector4Property;
	public extern var CapturedVector2DProperty(get, never): Vector2D;
	public inline extern function get_CapturedVector2DProperty(): Vector2D return this.CapturedVector2DProperty;
	public extern var CapturedIntPointProperty(get, never): IntPoint;
	public inline extern function get_CapturedIntPointProperty(): IntPoint return this.CapturedIntPointProperty;
	public extern var CapturedUObjectArrayProperty(get, never): TArray<ucpp.Ptr<Object.ConstObject>>;
	public inline extern function get_CapturedUObjectArrayProperty(): TArray<ucpp.Ptr<Object.ConstObject>> return this.CapturedUObjectArrayProperty;
	public extern var CapturedVectorArrayProperty(get, never): TArray<Vector>;
	public inline extern function get_CapturedVectorArrayProperty(): TArray<Vector> return this.CapturedVectorArrayProperty;
}

@:forward
@:nativeGen
@:native("VariantManagerTestActor*")
abstract VariantManagerTestActorPtr(ucpp.Ptr<VariantManagerTestActor>) from ucpp.Ptr<VariantManagerTestActor> to ucpp.Ptr<VariantManagerTestActor>{
	@:from
	public static extern inline function fromValue(v: VariantManagerTestActor): VariantManagerTestActorPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): VariantManagerTestActor {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}