// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWebMPlatFileMediaSourceFactory")
@:include("WebMFileMediaSourceFactory.h")
@:valueType
extern class WebMPlatFileMediaSourceFactory extends Factory {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstWebMPlatFileMediaSourceFactory(WebMPlatFileMediaSourceFactory) from WebMPlatFileMediaSourceFactory {
}

@:forward
@:nativeGen
@:native("WebMPlatFileMediaSourceFactory*")
abstract WebMPlatFileMediaSourceFactoryPtr(ucpp.Ptr<WebMPlatFileMediaSourceFactory>) from ucpp.Ptr<WebMPlatFileMediaSourceFactory> to ucpp.Ptr<WebMPlatFileMediaSourceFactory>{
	@:from
	public static extern inline function fromValue(v: WebMPlatFileMediaSourceFactory): WebMPlatFileMediaSourceFactoryPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): WebMPlatFileMediaSourceFactory {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}