// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWidgetFieldNotificationExtension")
@:include("Binding/WidgetFieldNotificationExtension.h")
@:valueType
extern class WidgetFieldNotificationExtension extends UserWidgetExtension {

	public static function StaticClass(): ucpp.Ptr<Class>;
}

@:forward()
@:nativeGen
abstract ConstWidgetFieldNotificationExtension(WidgetFieldNotificationExtension) from WidgetFieldNotificationExtension {
}

@:forward
@:nativeGen
@:native("WidgetFieldNotificationExtension*")
abstract WidgetFieldNotificationExtensionPtr(ucpp.Ptr<WidgetFieldNotificationExtension>) from ucpp.Ptr<WidgetFieldNotificationExtension> to ucpp.Ptr<WidgetFieldNotificationExtension>{
	@:from
	public static extern inline function fromValue(v: WidgetFieldNotificationExtension): WidgetFieldNotificationExtensionPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): WidgetFieldNotificationExtension {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}