// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("UWidgetBlueprintThumbnailRenderer")
@:include("WidgetBlueprintThumbnailRenderer.h")
@:structAccess
extern class WidgetBlueprintThumbnailRenderer extends DefaultSizedThumbnailRenderer {

	public static function StaticClass(): cpp.Star<Class>;
}

@:forward()
@:nativeGen
abstract ConstWidgetBlueprintThumbnailRenderer(WidgetBlueprintThumbnailRenderer) from WidgetBlueprintThumbnailRenderer {
}

@:forward
@:nativeGen
@:native("WidgetBlueprintThumbnailRenderer*")
abstract WidgetBlueprintThumbnailRendererPtr(cpp.Star<WidgetBlueprintThumbnailRenderer>) from cpp.Star<WidgetBlueprintThumbnailRenderer> to cpp.Star<WidgetBlueprintThumbnailRenderer>{
	@:from
	public static extern inline function fromValue(v: WidgetBlueprintThumbnailRenderer): WidgetBlueprintThumbnailRendererPtr {
		return untyped __cpp__("&({0})", v);
	}

	@:to
	public extern inline function asValue(): WidgetBlueprintThumbnailRenderer {
		return untyped __cpp__("*({0})", this);
	}

	public extern inline function delete(): Void {
		untyped __cpp__("delete ({0})", this);
	}
}