// Generated by Haxe-UnrealEngine5 (https://github.com/RobertBorghese/Haxe-UnrealEngine5)
package ue;

@:native("FWorldPartitionRuntimeCellDebugInfo")
@:include("WorldPartition/WorldPartitionRuntimeCell.h")
@:valueType
extern class WorldPartitionRuntimeCellDebugInfo {
	public var Name: FString;
	public var GridName: FName;
	public var CoordX: ucpp.num.Int64;
	public var CoordY: ucpp.num.Int64;
	public var CoordZ: ucpp.num.Int64;

	@:native("FWorldPartitionRuntimeCellDebugInfo") public function new();
	@:native("FWorldPartitionRuntimeCellDebugInfo") public static function make(Name: FString, GridName: FName, CoordX: ucpp.num.Int64, CoordY: ucpp.num.Int64, CoordZ: ucpp.num.Int64): WorldPartitionRuntimeCellDebugInfo ;
}